In [ ]:
# %pip install numpy==1.26.4, scipy==1.13.1
# %pip install -U ipywidgets
# %pip install -U gradio
# %pip install txagent
# %pip install tooluniverse

Requirement already satisfied: numpy==1.26.4 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (1.26.4)
Requirement already satisfied: scipy==1.13.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (1.13.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: ipywidgets in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipywidgets) (8.37.0)
Requirement already satisfied: traitlets>=4.3.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: decorator in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: exceptiongroup in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (1.3.0)
Requirement already satisfied: jedi>=0.16 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.15.0)
Requirement already satisfied: wcwidth in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure_eval in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: gradio in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (3.35.2)
Collecting gradio
  Using cached gradio-6.0.1-py3-none-any.whl.metadata (16 kB)
Collecting aiofiles<25.0,>=22.0 (from gradio)
  Downloading aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (4.9.0)
Requirement already satisfied: brotli>=1.1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (0.116.1)
Requirement already satisfied: ffmpy in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (1.0.0)
Collecting gradio-client==2.0.0 (from gradio)
  Downloading gradio_client-2.0.0-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio)
  Downloading groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (0.36.0)
Requirement already satisfied: jinja2<4.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (1.26.4)
Requirement already satisfied: orjson~=3.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (3.11.4)
Requirement already satisfied: packaging in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (25.0)
Requirement already satisfied: pandas<3.0,>=1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (2.3.3)
Requirement already satisfied: pillow<13.0,>=8.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (11.3.0)
Collecting pydantic<=2.12.4,>=2.11.10 (from gradio)
  Downloading pydantic-2.12.4-py3-none-any.whl.metadata (89 kB)
Requirement already satisfied: pydub in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (0.0.20)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (6.0.2)
Collecting safehttpx<0.2.0,>=0.1.7 (from gradio)
  Downloading safehttpx-0.1.7-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: semantic-version~=2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (0.47.1)
Collecting tomlkit<0.14.0,>=0.12.0 (from gradio)
  Downloading tomlkit-0.13.3-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: typer<1.0,>=0.12 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (0.20.0)
Requirement already satisfied: typing-extensions~=4.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio) (0.35.0)
Requirement already satisfied: fsspec in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from gradio-client==2.0.0->gradio) (2023.10.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: idna>=2.8 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: certifi in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from httpx<1.0,>=0.24.1->gradio) (2025.7.9)
Requirement already satisfied: httpcore==1.* in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.18.0)
Requirement already satisfied: requests in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pydantic<=2.12.4,>=2.11.10->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pydantic<=2.12.4,>=2.11.10->gradio) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pydantic<=2.12.4,>=2.11.10->gradio) (0.4.2)
Requirement already satisfied: click>=8.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from typer<1.0,>=0.12->gradio) (14.2.0)
Requirement already satisfied: six>=1.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests->huggingface-hub<2.0,>=0.33.5->gradio) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests->huggingface-hub<2.0,>=0.33.5->gradio) (2.5.0)
Downloading gradio-6.0.1-py3-none-any.whl (21.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.6/21.6 MB 127.7 MB/s  0:00:00
Downloading gradio_client-2.0.0-py3-none-any.whl (315 kB)
Downloading aiofiles-24.1.0-py3-none-any.whl (15 kB)
Downloading groovy-0.1.2-py3-none-any.whl (14 kB)
Downloading pydantic-2.12.4-py3-none-any.whl (463 kB)
Downloading safehttpx-0.1.7-py3-none-any.whl (9.0 kB)
Downloading tomlkit-0.13.3-py3-none-any.whl (38 kB)
Installing collected packages: tomlkit, groovy, aiofiles, pydantic, safehttpx, gradio-client, gradio
  Attempting uninstall: aiofiles
    Found existing installation: aiofiles 25.1.0
    Uninstalling aiofiles-25.1.0:
      Successfully uninstalled aiofiles-25.1.0
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.12.5
    Uninstalling pydantic-2.12.5:
      Successfully uninstalled pydantic-2.12.5
  Attempting uninstall: gradio-client0m━━━━━━━━━━━━━━━━━━━━━━ 3/7 [pydantic]
    Found existing installation: gradio_client 0.2.9━━━━━━━━━━ 3/7 [pydantic]
    Uninstalling gradio_client-0.2.9:90m━━━━━━━━━━━━━━━━━━━━━━ 3/7 [pydantic]
      Successfully uninstalled gradio_client-0.2.9━━━━━━━━━━━━ 3/7 [pydantic]
  Attempting uninstall: gradio╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [pydantic]
    Found existing installation: gradio 3.35.2━━━━━━━━━━━━━━━━ 3/7 [pydantic]
    Uninstalling gradio-3.35.2:━━━━━━━━━━━━━━━━━━━━━━ 3/7 [pydantic]
      Successfully uninstalled gradio-3.35.2━━━━━━━━━━━━━━━━━━ 3/7 [pydantic]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [gradio]2m6/7 [gradio]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llava-med 1.5.0 requires bitsandbytes==0.41.0, which is not installed.
llava-med 1.5.0 requires accelerate==0.21.0, but you have accelerate 0.30.1 which is incompatible.
llava-med 1.5.0 requires gradio==3.35.2, but you have gradio 6.0.1 which is incompatible.
llava-med 1.5.0 requires gradio_client==0.2.9, but you have gradio-client 2.0.0 which is incompatible.
llava-med 1.5.0 requires httpx==0.24.0, but you have httpx 0.28.1 which is incompatible.
llava-med 1.5.0 requires openai==1.12.0, but you have openai 2.8.1 which is incompatible.
llava-med 1.5.0 requires pydantic<2,>=1, but you have pydantic 2.12.4 which is incompatible.
llava-med 1.5.0 requires transformers==4.36.2, but you have transformers 4.57.3 which is incompatible.
mlflow-skinny 2.22.1 requires cachetools<6,>=5.0.0, but you have cachetools 6.2.2 which is incompatible.
mlflow-skinny 2.22.1 requires packaging<25, but you have packaging 25.0 which is incompatible.
tooluniverse 1.0.14.1 requires numpy>=2.2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed aiofiles-24.1.0 gradio-6.0.1 gradio-client-2.0.0 groovy-0.1.2 pydantic-2.12.4 safehttpx-0.1.7 tomlkit-0.13.3
Note: you may need to restart the kernel to use updated packages.

In [2]:
from txagent import ToolRAGModel
from tooluniverse import ToolUniverse

tool_universe = ToolUniverse()
tool_universe.load_tools()

rag_model_name = 'mims-harvard/ToolRAG-T1-GTE-Qwen2-1.5B'
tool_rag = ToolRAGModel(rag_model_name)

ℹ️  Number of tools after load tools: 768
⚠️  Some tools will not be loaded due to missing API keys: HF_TOKEN, BOLTZ_MCP_SERVER_HOST, USPTO_MCP_SERVER_HOST, USPTO_API_KEY, At least one of: OPENAI_API_KEY, AZURE_OPENAI_API_KEY, HF_TOKEN, TXAGENT_MCP_SERVER_HOST, EXPERT_FEEDBACK_MCP_SERVER_URL
ℹ️  Generated API key template: .env.template. Copy this file to .env and fill in your API keys
⚠️  Some tools will not be loaded due to missing API keys: HF_TOKEN, BOLTZ_MCP_SERVER_HOST, USPTO_MCP_SERVER_HOST, USPTO_API_KEY, At least one of: OPENAI_API_KEY, AZURE_OPENAI_API_KEY, HF_TOKEN, TXAGENT_MCP_SERVER_HOST, EXPERT_FEEDBACK_MCP_SERVER_URL
ℹ️  Generated API key template: .env.template. Copy this file to .env and fill in your API keys

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/80.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/370 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

In [3]:
tool_rag.load_tool_desc_embedding(tool_universe)

get the md value of tools: 73772afa763b9c9462d49ac5bc2bd1e2

In [ ]:
query = "Given a 50-year-old patient experiencing severe acute pain and considering the use of the newly approved medication, Journavx, how should the dosage be adjusted considering the presence of moderate hepatic impairment?"
 
retrieved_tools = tool_rag.rag_infer(query, top_k=5)
retrieved_tools

['FDA_get_dosage_and_storage_information_by_drug_name',
 'FDA_get_population_use_info_by_drug_name']

In [1]:
import os
# Use GPU 1 (GPU 0 is full)
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
# Use vLLM V0 engine to support logits processors
os.environ["VLLM_USE_V1"] = "0"

from txagent import TxAgent

model_name = 'mims-harvard/TxAgent-T1-Llama-3.1-8B'
rag_model_name = 'mims-harvard/ToolRAG-T1-GTE-Qwen2-1.5B'

multiagent = False
max_round = 20
init_rag_num = 0
step_rag_num = 10

agent = TxAgent(model_name,
                rag_model_name,
                enable_summary=True)
agent.init_model()

INFO 12-02 09:16:54 [__init__.py:239] Automatically detected platform cuda.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

model_name: mims-harvard/TxAgent-T1-Llama-3.1-8B
tokenizer: None
terminators: None
rag_model_name: mims-harvard/ToolRAG-T1-GTE-Qwen2-1.5B
tool_files_dict: None
model: None
rag_model: <txagent.toolrag.ToolRAGModel object at 0x7609a0c65570>
tooluniverse: None
prompt_multi_step: You are a helpful assistant that will solve problems through detailed, step-by-step reasoning and actions based on your reasoning. Typically, your actions will use the provided functions. You have access to the following functions.
self_prompt: Strictly follow the instruction.
chat_prompt: You are helpful assistant to chat with the user.
enable_finish: True
enable_rag: True
enable_summary: True
summary_mode: step
summary_skip_last_k: 0
summary_context_length: None
init_rag_num: 0
step_rag_num: 10
force_finish: True
avoid_repeat: True
seed: None
enable_checker: False
additional_default_tools: None

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 12-02 09:17:00 [config.py:2832] Downcasting torch.float32 to torch.float16.
INFO 12-02 09:17:07 [config.py:689] This model supports multiple tasks: {'reward', 'generate', 'score', 'classify', 'embed'}. Defaulting to 'generate'.
WARNING 12-02 09:17:07 [arg_utils.py:1592] Chunked prefill is enabled by default for models with max_model_len > 32K. Chunked prefill might not work with some features or models. If you encounter any issues, please disable by launching with --enable-chunked-prefill=False.
INFO 12-02 09:17:07 [config.py:1901] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 12-02 09:17:07 [llm_engine.py:243] Initializing a V0 LLM engine (v0.8.4) with config: model='mims-harvard/TxAgent-T1-Llama-3.1-8B', speculative_config=None, tokenizer='mims-harvard/TxAgent-T1-Llama-3.1-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=mims-harvard/TxAgent-T1-Llama-3.1-8B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False,
INFO 12-02 09:17:07 [config.py:689] This model supports multiple tasks: {'reward', 'generate', 'score', 'classify', 'embed'}. Defaulting to 'generate'.
WARNING 12-02 09:17:07 [arg_utils.py:1592] Chunked prefill is enabled by default for models with max_model_len > 32K. Chunked prefill might not work with some features or models. If you encounter any issues, please disable by launching with --enable-chunked-prefill=False.
INFO 12-02 09:17:07 [config.py:1901] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 12-02 09:17:07 [llm_engine.py:243] Initializing a V0 LLM engine (v0.8.4) with config: model='mims-harvard/TxAgent-T1-Llama-3.1-8B', speculative_config=None, tokenizer='mims-harvard/TxAgent-T1-Llama-3.1-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=mims-harvard/TxAgent-T1-Llama-3.1-8B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False,
INFO 12-02 09:17:09 [cuda.py:292] Using Flash Attention backend.
INFO 12-02 09:17:09 [cuda.py:292] Using Flash Attention backend.
INFO 12-02 09:17:10 [parallel_state.py:959] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 12-02 09:17:10 [model_runner.py:1110] Starting to load model mims-harvard/TxAgent-T1-Llama-3.1-8B...
INFO 12-02 09:17:10 [parallel_state.py:959] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 12-02 09:17:10 [model_runner.py:1110] Starting to load model mims-harvard/TxAgent-T1-Llama-3.1-8B...
INFO 12-02 09:17:10 [weight_utils.py:265] Using model weights format ['*.safetensors']
INFO 12-02 09:17:10 [weight_utils.py:265] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/7 [00:00<?, ?it/s]

INFO 12-02 09:17:14 [loader.py:458] Loading weights took 4.12 seconds
INFO 12-02 09:17:14 [model_runner.py:1146] Model loading took 14.9889 GiB and 4.541323 seconds
INFO 12-02 09:17:14 [model_runner.py:1146] Model loading took 14.9889 GiB and 4.541323 seconds
INFO 12-02 09:17:16 [worker.py:267] Memory profiling takes 1.20 seconds
INFO 12-02 09:17:16 [worker.py:267] the current vLLM instance can use total_gpu_memory (79.15GiB) x gpu_memory_utilization (0.90) = 71.24GiB
INFO 12-02 09:17:16 [worker.py:267] model weights take 14.99GiB; non_torch_memory takes 0.09GiB; PyTorch activation peak memory takes 1.19GiB; the rest of the memory reserved for KV Cache is 54.97GiB.
INFO 12-02 09:17:16 [worker.py:267] Memory profiling takes 1.20 seconds
INFO 12-02 09:17:16 [worker.py:267] the current vLLM instance can use total_gpu_memory (79.15GiB) x gpu_memory_utilization (0.90) = 71.24GiB
INFO 12-02 09:17:16 [worker.py:267] model weights take 14.99GiB; non_torch_memory takes 0.09GiB; PyTorch activation peak memory takes 1.19GiB; the rest of the memory reserved for KV Cache is 54.97GiB.
INFO 12-02 09:17:16 [executor_base.py:112] # cuda blocks: 28143, # CPU blocks: 2048
INFO 12-02 09:17:16 [executor_base.py:117] Maximum concurrency for 131072 tokens per request: 3.44x
INFO 12-02 09:17:16 [executor_base.py:112] # cuda blocks: 28143, # CPU blocks: 2048
INFO 12-02 09:17:16 [executor_base.py:117] Maximum concurrency for 131072 tokens per request: 3.44x
INFO 12-02 09:17:19 [model_runner.py:1456] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 12-02 09:17:19 [model_runner.py:1456] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.

Capturing CUDA graph shapes:   0%|          | 0/35 [00:00<?, ?it/s]

INFO 12-02 09:17:40 [model_runner.py:1598] Graph capturing finished in 21 secs, took 0.83 GiB
INFO 12-02 09:17:40 [llm_engine.py:449] init engine (profile, create kv cache, warmup model) took 25.88 seconds
INFO 12-02 09:17:40 [llm_engine.py:449] init engine (profile, create kv cache, warmup model) took 25.88 seconds
ℹ️  Number of tools after load tools: 768
⚠️  Some tools will not be loaded due to missing API keys: At least one of: OPENAI_API_KEY, AZURE_OPENAI_API_KEY, HF_TOKEN, TXAGENT_MCP_SERVER_HOST, USPTO_API_KEY, HF_TOKEN, BOLTZ_MCP_SERVER_HOST, USPTO_MCP_SERVER_HOST, EXPERT_FEEDBACK_MCP_SERVER_URL
ℹ️  Generated API key template: .env.template. Copy this file to .env and fill in your API keys
ℹ️  Number of tools after load tools: 768
⚠️  Some tools will not be loaded due to missing API keys: At least one of: OPENAI_API_KEY, AZURE_OPENAI_API_KEY, HF_TOKEN, TXAGENT_MCP_SERVER_HOST, USPTO_API_KEY, HF_TOKEN, BOLTZ_MCP_SERVER_HOST, USPTO_MCP_SERVER_HOST, EXPERT_FEEDBACK_MCP_SERVER_URL
ℹ️  Generated API key template: .env.template. Copy this file to .env and fill in your API keys
get the md value of tools: 73772afa763b9c9462d49ac5bc2bd1e2
get the md value of tools: 73772afa763b9c9462d49ac5bc2bd1e2

In [2]:
# question = "Given a 50-year-old patient experiencing severe acute pain and considering the use of the newly approved medication, Journavx, how should the dosage be adjusted considering the presence of moderate hepatic impairment?"

question = 'Question: A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ago and has been worsening despite drinking more water and taking cranberry extract. She otherwise feels well and is followed by a doctor for her pregnancy. Her temperature is 97.7°F (36.5°C), blood pressure is 122/77 mmHg, pulse is 80/min, respirations are 19/min, and oxygen saturation is 98% on room air. Physical exam is notable for an absence of costovertebral angle tenderness and a gravid uterus. Which of the following is the best treatment for this patient?\nOptions: Ampicillin / Ceftriaxone / Ciprofloxacin / Doxycycline / Nitrofurantoin'

# question = 'A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ago and has been worsening despite drinking more water and taking cranberry extract. She otherwise feels well and is followed by a doctor for her pregnancy. Her temperature is 97.7°F (36.5°C), blood pressure is 122/77 mmHg, pulse is 80/min, respirations are 19/min, and oxygen saturation is 98% on room air. Physical exam is notable for an absence of costovertebral angle tenderness and a gravid uterus. Which of the following is the best treatment for this patient?'

response = agent.run_multistep_agent(
    question,
    temperature=0.3,
    max_new_tokens=1024,
    max_token=90240,
    call_agent=multiagent,
    max_round=max_round)


print("=======================================================================")
response

start
⚠️  The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
Finish tool is added
⚠️  The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
Finish tool is added
⚠️  The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
Tool_RAG tool is added
Tool_RAG tool is added

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

To determine the best treatment for the pregnant woman experiencing burning upon urination, I need to gather information on the indications and safety of each antibiotic option during pregnancy. I will start by retrieving the indications for each of the antibiotics listed: Ampicillin, Ceftriaxone, Ciprofloxacin, Doxycycline, and Nitrofurantoin. [TOOL_CALLS][{"name": "Tool_RAG", "arguments": {"description": "Get the usage and indications for a specific drug name.", "limit": 5}}]
Tool Call: {'name': 'Tool_RAG', 'arguments': {'description': 'Get the usage and indications for a specific drug name.', 'limit': 5}}
Tool Call Result: ['FDA_get_pregnancy_effects_info_by_drug_name', 'FDA_get_population_use_info_by_drug_name', 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'euhealthinfo_search_births', 'FDA_get_labor_and_delivery_info_by_drug_name', 'FDA_get_drug_names_by_pregnancy_effects_info', 'FDA_get_risk_info_by_drug_name', 'FDA_get_teratogenic_effects_by_drug_name', 'FDA_get_drug_names_by_population_use', 'FDA_get_drug_name_by_pregnancy_or_breastfeeding_info']

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

To evaluate the safety of each antibiotic option during pregnancy, I will retrieve pregnancy-related safety information for each of the antibiotics: Ampicillin, Ceftriaxone, Ciprofloxacin, Doxycycline, and Nitrofurantoin. This will help determine which option is safest for the pregnant woman. [TOOL_CALLS][{"name": "FDA_get_pregnancy_or_breastfeeding_info_by_drug_name", "arguments": {"drug_name": "Ampicillin", "limit": 1}}, {"name": "FDA_get_pregnancy_or_breastfeeding_info_by_drug_name", "arguments": {"drug_name": "Ceftriaxone", "limit": 1}}, {"name": "FDA_get_pregnancy_or_breastfeeding_info_by_drug_name", "arguments": {"drug_name": "Ciprofloxacin", "limit": 1}}, {"name": "FDA_get_pregnancy_or_breastfeeding_info_by_drug_name", "arguments": {"drug_name": "Doxycycline", "limit": 1}}, {"name": "FDA_get_pregnancy_or_breastfeeding_info_by_drug_name", "arguments": {"drug_name": "Nitrofurantoin", "limit": 1}}]
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Ampicillin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ampicillin)+openfda.generic_name:(AMPICILLIN))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 54}, 'results': [{'openfda.brand_name': ['Ampicillin and Sulbactam'], 'openfda.generic_name': ['AMPICILLIN SODIUM AND SULBACTAM SODIUM'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['Pregnancy Reproduction studies have been performed in mice, rats, and rabbits at doses up to ten (10) times the human dose and have revealed no evidence of impaired fertility or harm to the fetus due to ampicillin and sulbactam for injection. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproduction studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed (see PRECAUTIONS Drug/Laboratory Test Interactions section).']}]}
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Ceftriaxone', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ceftriaxone)+openfda.generic_name:(CEFTRIAXONE))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 54}, 'results': [{'openfda.brand_name': ['Ampicillin and Sulbactam'], 'openfda.generic_name': ['AMPICILLIN SODIUM AND SULBACTAM SODIUM'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['Pregnancy Reproduction studies have been performed in mice, rats, and rabbits at doses up to ten (10) times the human dose and have revealed no evidence of impaired fertility or harm to the fetus due to ampicillin and sulbactam for injection. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproduction studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed (see PRECAUTIONS Drug/Laboratory Test Interactions section).']}]}
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Ceftriaxone', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ceftriaxone)+openfda.generic_name:(CEFTRIAXONE))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 34}, 'results': [{'openfda.brand_name': ['Ceftriaxone Sodium'], 'openfda.generic_name': ['CEFTRIAXONE SODIUM'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['Pregnancy Teratogenic Effects Reproductive studies have been performed in mice and rats at doses up to 20 times the usual human dose and have no evidence of embryotoxicity, fetotoxicity or teratogenicity. In primates, no embryotoxicity or teratogenicity was demonstrated at a dose approximately 3 times the human dose. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproductive studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed. Nonteratogenic Effects In rats, in the Segment I (fertility and general reproduction) and Segment III (perinatal and postnatal) studies with intravenously administered ceftriaxone, no adverse effects were noted on various reproductive parameters during gestation and lactation, including postnatal growth, functional behavior and reproductive ability of the offspring, at doses of 586 mg/kg/day or less.']}]}
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Ciprofloxacin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ciprofloxacin)+openfda.generic_name:(CIPROFLOXACIN))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 34}, 'results': [{'openfda.brand_name': ['Ceftriaxone Sodium'], 'openfda.generic_name': ['CEFTRIAXONE SODIUM'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['Pregnancy Teratogenic Effects Reproductive studies have been performed in mice and rats at doses up to 20 times the usual human dose and have no evidence of embryotoxicity, fetotoxicity or teratogenicity. In primates, no embryotoxicity or teratogenicity was demonstrated at a dose approximately 3 times the human dose. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproductive studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed. Nonteratogenic Effects In rats, in the Segment I (fertility and general reproduction) and Segment III (perinatal and postnatal) studies with intravenously administered ceftriaxone, no adverse effects were noted on various reproductive parameters during gestation and lactation, including postnatal growth, functional behavior and reproductive ability of the offspring, at doses of 586 mg/kg/day or less.']}]}
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Ciprofloxacin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ciprofloxacin)+openfda.generic_name:(CIPROFLOXACIN))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 181}, 'results': [{'openfda.brand_name': ['CILOXAN'], 'openfda.generic_name': ['CIPROFLOXACIN HYDROCHLORIDE'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['Pregnancy: Reproduction studies have been performed in rats and mice at doses up to six times the usual daily human oral dose and have revealed no evidence of impaired fertility or harm to the fetus due to ciprofloxacin. In rabbits, as with most antimicrobial agents, ciprofloxacin (30 and 100 mg/kg orally) produced gastrointestinal disturbances resulting in maternal weight loss and an increased incidence of abortion. No teratogenicity was observed at either dose. After intravenous administration, at doses up to 20 mg/kg, no maternal toxicity was produced and no embryotoxicity or teratogenicity was observed. There are no adequate and well controlled studies in pregnant women. CILOXAN ® (ciprofloxacin ophthalmic ointment) 0.3% should be used during pregnancy only if the potential benefit justifies the potential risk to the fetus.']}]}
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Doxycycline', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Doxycycline)+openfda.generic_name:(DOXYCYCLINE))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 181}, 'results': [{'openfda.brand_name': ['CILOXAN'], 'openfda.generic_name': ['CIPROFLOXACIN HYDROCHLORIDE'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['Pregnancy: Reproduction studies have been performed in rats and mice at doses up to six times the usual daily human oral dose and have revealed no evidence of impaired fertility or harm to the fetus due to ciprofloxacin. In rabbits, as with most antimicrobial agents, ciprofloxacin (30 and 100 mg/kg orally) produced gastrointestinal disturbances resulting in maternal weight loss and an increased incidence of abortion. No teratogenicity was observed at either dose. After intravenous administration, at doses up to 20 mg/kg, no maternal toxicity was produced and no embryotoxicity or teratogenicity was observed. There are no adequate and well controlled studies in pregnant women. CILOXAN ® (ciprofloxacin ophthalmic ointment) 0.3% should be used during pregnancy only if the potential benefit justifies the potential risk to the fetus.']}]}
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Doxycycline', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Doxycycline)+openfda.generic_name:(DOXYCYCLINE))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 146}, 'results': [{'openfda.brand_name': ['doxycycline'], 'openfda.generic_name': ['DOXYCYCLINE'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['Pregnancy: Teratogenic Effects There are no adequate and well-controlled studies on the use of doxycycline in pregnant women. The vast majority of reported experience with doxycycline during human pregnancy is short-term, first trimester exposure. There are no human data available to assess the effects of long-term therapy of doxycycline in pregnant women, such as that proposed for treatment of anthrax exposure. An expert review of published data on experiences with doxycycline use during pregnancy by TERIS-the Teratogen Information System-concluded that therapeutic doses during pregnancy are unlikely to pose a substantial teratogenic risk (the quantity and quality of data were assessed as limited to fair), but the data are insufficient to state that there is no risk. 1 A case-control study (18,515 mothers of infants with congenital anomalies and 32,804 mothers of infants with no congenital anomalies) shows a weak but marginally statistically significant association with total malformations and use of doxycycline anytime during pregnancy. Sixty-three (0.19%) of the controls and fifty-six (0.30%) of the cases were treated with doxycycline. This association was not seen when the analysis was confined to maternal treatment during the period of organogenesis (i.e., in the second and third months of gestation) with the exception of a marginal relationship with neural tube defect based on only two exposed cases. 2 A small prospective study of 81 pregnancies describes 43 pregnant women treated for 10 days with doxycycline during early first trimester. All mothers reported their exposed infants were normal at 1 year of age. 3 Nonteratogenic Effects (See WARNINGS .)']}]}
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Nitrofurantoin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Nitrofurantoin)+openfda.generic_name:(NITROFURANTOIN))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 146}, 'results': [{'openfda.brand_name': ['doxycycline'], 'openfda.generic_name': ['DOXYCYCLINE'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['Pregnancy: Teratogenic Effects There are no adequate and well-controlled studies on the use of doxycycline in pregnant women. The vast majority of reported experience with doxycycline during human pregnancy is short-term, first trimester exposure. There are no human data available to assess the effects of long-term therapy of doxycycline in pregnant women, such as that proposed for treatment of anthrax exposure. An expert review of published data on experiences with doxycycline use during pregnancy by TERIS-the Teratogen Information System-concluded that therapeutic doses during pregnancy are unlikely to pose a substantial teratogenic risk (the quantity and quality of data were assessed as limited to fair), but the data are insufficient to state that there is no risk. 1 A case-control study (18,515 mothers of infants with congenital anomalies and 32,804 mothers of infants with no congenital anomalies) shows a weak but marginally statistically significant association with total malformations and use of doxycycline anytime during pregnancy. Sixty-three (0.19%) of the controls and fifty-six (0.30%) of the cases were treated with doxycycline. This association was not seen when the analysis was confined to maternal treatment during the period of organogenesis (i.e., in the second and third months of gestation) with the exception of a marginal relationship with neural tube defect based on only two exposed cases. 2 A small prospective study of 81 pregnancies describes 43 pregnant women treated for 10 days with doxycycline during early first trimester. All mothers reported their exposed infants were normal at 1 year of age. 3 Nonteratogenic Effects (See WARNINGS .)']}]}
Tool Call: {'name': 'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name', 'arguments': {'drug_name': 'Nitrofurantoin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Nitrofurantoin)+openfda.generic_name:(NITROFURANTOIN))+AND+(_exists_:pregnancy_or_breast_feeding+_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 76}, 'results': [{'openfda.brand_name': ['Nitrofurantoin'], 'openfda.generic_name': ['NITROFURANTOIN'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['8.1 Pregnancy Risk Summary Nitrofurantoin is contraindicated in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia in the infant (see Clinical Considerations). Published epidemiological studies, including cohort studies and case control studies, have reported inconsistent findings related to nitrofurantoin use during the first trimester and risk of major birth defects. These studies cannot definitively establish the presence or absence of risk due to several methodological limitations. The limited number of epidemiological studies available have not identified drug-associated risks of major birth defects, miscarriage or other adverse maternal or fetal outcomes. In animal reproduction studies, no fetotoxicity was observed when nitrofurantoin was administered orally to pregnant rats and rabbits, during organogenesis, at up to 6 times the recommended human dose (see Data ). The background risk of major birth defects and miscarriage for the indicated population is unknown. All pregnancies have a background risk of birth defect, loss, or other adverse outcomes. In the U.S. general population, the estimated background risk of major birth defects and miscarriage in clinically recognized pregnancies is 2% to 4% and 15% to 20%, respectively. Clinical Considerations Fetal/Neonatal Adverse Reactions Nitrofurantoin is not recommended in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia due to immature erythrocyte enzyme systems (glutathione instability) [see Contraindications (4) and Warnings and Precautions (5.4)]. Data Animal Data Several reproduction studies have been performed in rabbits and rats at doses up to six times the human dose and have revealed no harm to the fetus due to nitrofurantoin. In a single published study conducted in mice at 68 times the human dose (based on mg/kg administered to the dam), growth retardation and a low incidence of minor and common malformations were observed. However, at 25 times the human dose, fetal malformations were not observed. Nitrofurantoin has been shown in one published transplacental carcinogenicity study to induce lung papillary adenomas in the F1 generation mice at doses 19 times the human dose on a mg/kg basis. The relationship of this finding to potential human carcinogenesis is presently unknown.']}]}
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 76}, 'results': [{'openfda.brand_name': ['Nitrofurantoin'], 'openfda.generic_name': ['NITROFURANTOIN'], 'pregnancy_or_breast_feeding': None, 'pregnancy': ['8.1 Pregnancy Risk Summary Nitrofurantoin is contraindicated in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia in the infant (see Clinical Considerations). Published epidemiological studies, including cohort studies and case control studies, have reported inconsistent findings related to nitrofurantoin use during the first trimester and risk of major birth defects. These studies cannot definitively establish the presence or absence of risk due to several methodological limitations. The limited number of epidemiological studies available have not identified drug-associated risks of major birth defects, miscarriage or other adverse maternal or fetal outcomes. In animal reproduction studies, no fetotoxicity was observed when nitrofurantoin was administered orally to pregnant rats and rabbits, during organogenesis, at up to 6 times the recommended human dose (see Data ). The background risk of major birth defects and miscarriage for the indicated population is unknown. All pregnancies have a background risk of birth defect, loss, or other adverse outcomes. In the U.S. general population, the estimated background risk of major birth defects and miscarriage in clinically recognized pregnancies is 2% to 4% and 15% to 20%, respectively. Clinical Considerations Fetal/Neonatal Adverse Reactions Nitrofurantoin is not recommended in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia due to immature erythrocyte enzyme systems (glutathione instability) [see Contraindications (4) and Warnings and Precautions (5.4)]. Data Animal Data Several reproduction studies have been performed in rabbits and rats at doses up to six times the human dose and have revealed no harm to the fetus due to nitrofurantoin. In a single published study conducted in mice at 68 times the human dose (based on mg/kg administered to the dam), growth retardation and a low incidence of minor and common malformations were observed. However, at 25 times the human dose, fetal malformations were not observed. Nitrofurantoin has been shown in one published transplacental carcinogenicity study to induce lung papillary adenomas in the F1 generation mice at doses 19 times the human dose on a mg/kg basis. The relationship of this finding to potential human carcinogenesis is presently unknown.']}]}

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Based on the retrieved information, I need to analyze the safety profiles of each antibiotic during pregnancy to determine the best treatment option for the patient. The information indicates that Ampicillin, Ceftriaxone, and Ciprofloxacin have no evidence of harm to the fetus in animal studies, but there are no adequate and well-controlled studies in pregnant women. Doxycycline has some potential risks, and Nitrofurantoin is contraindicated at term due to potential hemolytic anemia. I will now focus on the specific indication of each drug for treating urinary tract infections, especially in pregnant women, to make a more informed decision. [TOOL_CALLS][{"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Ampicillin", "limit": 1}}, {"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Ceftriaxone", "limit": 1}}, {"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Ciprofloxacin", "limit": 1}}, {"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Doxycycline", "limit": 1}}, {"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Nitrofurantoin", "limit": 1}}]
Tool Call: {'name': 'FDA_get_population_use_info_by_drug_name', 'arguments': {'drug_name': 'Ampicillin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ampicillin)+openfda.generic_name:(AMPICILLIN))+AND+(_exists_:use_in_specific_populations)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Invalid Query:  {'code': 'NOT_FOUND', 'message': 'No matches found!'}
Tool Call Result: None
Tool Call: {'name': 'FDA_get_population_use_info_by_drug_name', 'arguments': {'drug_name': 'Ceftriaxone', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ceftriaxone)+openfda.generic_name:(CEFTRIAXONE))+AND+(_exists_:use_in_specific_populations)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Invalid Query:  {'code': 'NOT_FOUND', 'message': 'No matches found!'}
Tool Call Result: None
Tool Call: {'name': 'FDA_get_population_use_info_by_drug_name', 'arguments': {'drug_name': 'Ceftriaxone', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ceftriaxone)+openfda.generic_name:(CEFTRIAXONE))+AND+(_exists_:use_in_specific_populations)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 2}, 'results': [{'openfda.brand_name': ['Ceftriaxone'], 'openfda.generic_name': ['CEFTRIAXONE SODIUM'], 'use_in_specific_populations': ['8 USE IN SPECIFIC POPULATIONS Hepatic impairment: Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day. ( 5.7 ) Renal Impairment: This formulation of Ceftriaxone for Injection USP – Pharmacy Bulk Package bag, SmartPak ® should not be used in renally impaired patients who require less than the 1 gram dose of ceftriaxone. Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day. ( 5.7 ) Pediatric Patients: This formulation of Ceftriaxone for Injection USP – Pharmacy Bulk Package bag, SmartPak ® should not be used in pediatric patients who require less than the 1 gram adult dose of ceftriaxone. ( 2.2 , 8.4 ) 8.1 Pregnancy Pregnancy Category B. Reproductive studies have been performed in mice, rats, and primates at intravenous doses of 625, 586, and 84 mg/kg/day, respectively without evidence of embryotoxicity, fetotoxicity, or teratogenicity. These doses are approximately 1.5, 2.8, and 0.8 times the recommended clinical dose of 2 grams/day based on body surface area comparisons. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproductive studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed. Ceftriaxone was tested in a Segment III (pre-postnatal) study in rats at intravenous doses of up to 586 mg/kg/day approximately 2.8 times (mg/m 2 comparison) the recommended daily dose of 2 grams/day. No adverse effects were noted on various reproductive parameters during gestation and lactation, including postnatal growth, functional behavior, and reproductive ability of the offspring. 8.3 Nursing Mothers Ceftriaxone is excreted in human breast milk. Caution should be exercised when Ceftriaxone for Injection is administered to a nursing woman. 8.4 Pediatric Use Ceftriaxone for Injection USP, Pharmacy Bulk Package bag, SmartPak ® should not be used in pediatric patients who require less than the 1 gram dose of ceftriaxone. To prevent unintentional overdose, this product should not be used in pediatric patients who require less than the adult 1 gram dose of ceftriaxone. 8.5 Geriatric Use Of the total number of subjects in clinical studies of ceftriaxone sodium, 32% were 60 and over. No overall differences in safety or effectiveness were observed between these subjects and younger subjects, and other reported clinical experience has not identified differences in responses between the elderly and younger patients, but greater sensitivity of some older individuals cannot be ruled out. Ceftriaxone is known to be substantially excreted by the kidney, and the risk of adverse reactions to this drug may be greater in patients with impaired renal function. Because elderly patients are more likely to have decreased renal function, care should be taken in dose selection, and it may be useful to monitor renal function. The pharmacokinetics of ceftriaxone were only minimally altered in geriatric patients compared to healthy adult subjects, and dosage adjustments are not necessary for geriatric patients with ceftriaxone dosages up to 2 grams per day [see Clinical Pharmacology (12) ].']}]}
Tool Call: {'name': 'FDA_get_population_use_info_by_drug_name', 'arguments': {'drug_name': 'Ciprofloxacin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ciprofloxacin)+openfda.generic_name:(CIPROFLOXACIN))+AND+(_exists_:use_in_specific_populations)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 2}, 'results': [{'openfda.brand_name': ['Ceftriaxone'], 'openfda.generic_name': ['CEFTRIAXONE SODIUM'], 'use_in_specific_populations': ['8 USE IN SPECIFIC POPULATIONS Hepatic impairment: Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day. ( 5.7 ) Renal Impairment: This formulation of Ceftriaxone for Injection USP – Pharmacy Bulk Package bag, SmartPak ® should not be used in renally impaired patients who require less than the 1 gram dose of ceftriaxone. Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day. ( 5.7 ) Pediatric Patients: This formulation of Ceftriaxone for Injection USP – Pharmacy Bulk Package bag, SmartPak ® should not be used in pediatric patients who require less than the 1 gram adult dose of ceftriaxone. ( 2.2 , 8.4 ) 8.1 Pregnancy Pregnancy Category B. Reproductive studies have been performed in mice, rats, and primates at intravenous doses of 625, 586, and 84 mg/kg/day, respectively without evidence of embryotoxicity, fetotoxicity, or teratogenicity. These doses are approximately 1.5, 2.8, and 0.8 times the recommended clinical dose of 2 grams/day based on body surface area comparisons. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproductive studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed. Ceftriaxone was tested in a Segment III (pre-postnatal) study in rats at intravenous doses of up to 586 mg/kg/day approximately 2.8 times (mg/m 2 comparison) the recommended daily dose of 2 grams/day. No adverse effects were noted on various reproductive parameters during gestation and lactation, including postnatal growth, functional behavior, and reproductive ability of the offspring. 8.3 Nursing Mothers Ceftriaxone is excreted in human breast milk. Caution should be exercised when Ceftriaxone for Injection is administered to a nursing woman. 8.4 Pediatric Use Ceftriaxone for Injection USP, Pharmacy Bulk Package bag, SmartPak ® should not be used in pediatric patients who require less than the 1 gram dose of ceftriaxone. To prevent unintentional overdose, this product should not be used in pediatric patients who require less than the adult 1 gram dose of ceftriaxone. 8.5 Geriatric Use Of the total number of subjects in clinical studies of ceftriaxone sodium, 32% were 60 and over. No overall differences in safety or effectiveness were observed between these subjects and younger subjects, and other reported clinical experience has not identified differences in responses between the elderly and younger patients, but greater sensitivity of some older individuals cannot be ruled out. Ceftriaxone is known to be substantially excreted by the kidney, and the risk of adverse reactions to this drug may be greater in patients with impaired renal function. Because elderly patients are more likely to have decreased renal function, care should be taken in dose selection, and it may be useful to monitor renal function. The pharmacokinetics of ceftriaxone were only minimally altered in geriatric patients compared to healthy adult subjects, and dosage adjustments are not necessary for geriatric patients with ceftriaxone dosages up to 2 grams per day [see Clinical Pharmacology (12) ].']}]}
Tool Call: {'name': 'FDA_get_population_use_info_by_drug_name', 'arguments': {'drug_name': 'Ciprofloxacin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ciprofloxacin)+openfda.generic_name:(CIPROFLOXACIN))+AND+(_exists_:use_in_specific_populations)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Ampicillin, Ceftriaxone, and Ciprofloxacin have shown no evidence of harm to the fetus in animal studies but lack adequate human studies, Doxycycline has limited data suggesting a weak association with congenital anomalies, and Nitrofurantoin is contraindicated at term due to potential hemolytic anemia in infants.

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Based on the information retrieved, I need to focus on the specific indications of each antibiotic for treating urinary tract infections, especially in pregnant women. This will help determine which option is safest and most effective for the patient. I will now retrieve the indications for each of the antibiotics: Ampicillin, Ceftriaxone, Ciprofloxacin, Doxycycline, and Nitrofurantoin. [TOOL_CALLS][{"name": "FDA_get_pregnancy_effects_info_by_drug_name", "arguments": {"drug_name": "Ampicillin", "limit": 1}}, {"name": "FDA_get_pregnancy_effects_info_by_drug_name", "arguments": {"drug_name": "Ceftriaxone", "limit": 1}}, {"name": "FDA_get_pregnancy_effects_info_by_drug_name", "arguments": {"drug_name": "Ciprofloxacin", "limit": 1}}, {"name": "FDA_get_pregnancy_effects_info_by_drug_name", "arguments": {"drug_name": "Doxycycline", "limit": 1}}, {"name": "FDA_get_pregnancy_effects_info_by_drug_name", "arguments": {"drug_name": "Nitrofurantoin", "limit": 1}}]
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Ampicillin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ampicillin)+openfda.generic_name:(AMPICILLIN))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 54}, 'results': [{'openfda.brand_name': ['Ampicillin and Sulbactam'], 'openfda.generic_name': ['AMPICILLIN SODIUM AND SULBACTAM SODIUM'], 'pregnancy': ['Pregnancy Reproduction studies have been performed in mice, rats, and rabbits at doses up to ten (10) times the human dose and have revealed no evidence of impaired fertility or harm to the fetus due to ampicillin and sulbactam for injection. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproduction studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed (see PRECAUTIONS Drug/Laboratory Test Interactions section).']}]}
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Ceftriaxone', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ceftriaxone)+openfda.generic_name:(CEFTRIAXONE))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 54}, 'results': [{'openfda.brand_name': ['Ampicillin and Sulbactam'], 'openfda.generic_name': ['AMPICILLIN SODIUM AND SULBACTAM SODIUM'], 'pregnancy': ['Pregnancy Reproduction studies have been performed in mice, rats, and rabbits at doses up to ten (10) times the human dose and have revealed no evidence of impaired fertility or harm to the fetus due to ampicillin and sulbactam for injection. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproduction studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed (see PRECAUTIONS Drug/Laboratory Test Interactions section).']}]}
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Ceftriaxone', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ceftriaxone)+openfda.generic_name:(CEFTRIAXONE))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 34}, 'results': [{'openfda.brand_name': ['Ceftriaxone Sodium'], 'openfda.generic_name': ['CEFTRIAXONE SODIUM'], 'pregnancy': ['Pregnancy Teratogenic Effects Reproductive studies have been performed in mice and rats at doses up to 20 times the usual human dose and have no evidence of embryotoxicity, fetotoxicity or teratogenicity. In primates, no embryotoxicity or teratogenicity was demonstrated at a dose approximately 3 times the human dose. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproductive studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed. Nonteratogenic Effects In rats, in the Segment I (fertility and general reproduction) and Segment III (perinatal and postnatal) studies with intravenously administered ceftriaxone, no adverse effects were noted on various reproductive parameters during gestation and lactation, including postnatal growth, functional behavior and reproductive ability of the offspring, at doses of 586 mg/kg/day or less.']}]}
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Ciprofloxacin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ciprofloxacin)+openfda.generic_name:(CIPROFLOXACIN))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 34}, 'results': [{'openfda.brand_name': ['Ceftriaxone Sodium'], 'openfda.generic_name': ['CEFTRIAXONE SODIUM'], 'pregnancy': ['Pregnancy Teratogenic Effects Reproductive studies have been performed in mice and rats at doses up to 20 times the usual human dose and have no evidence of embryotoxicity, fetotoxicity or teratogenicity. In primates, no embryotoxicity or teratogenicity was demonstrated at a dose approximately 3 times the human dose. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproductive studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed. Nonteratogenic Effects In rats, in the Segment I (fertility and general reproduction) and Segment III (perinatal and postnatal) studies with intravenously administered ceftriaxone, no adverse effects were noted on various reproductive parameters during gestation and lactation, including postnatal growth, functional behavior and reproductive ability of the offspring, at doses of 586 mg/kg/day or less.']}]}
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Ciprofloxacin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Ciprofloxacin)+openfda.generic_name:(CIPROFLOXACIN))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 181}, 'results': [{'openfda.brand_name': ['CILOXAN'], 'openfda.generic_name': ['CIPROFLOXACIN HYDROCHLORIDE'], 'pregnancy': ['Pregnancy: Reproduction studies have been performed in rats and mice at doses up to six times the usual daily human oral dose and have revealed no evidence of impaired fertility or harm to the fetus due to ciprofloxacin. In rabbits, as with most antimicrobial agents, ciprofloxacin (30 and 100 mg/kg orally) produced gastrointestinal disturbances resulting in maternal weight loss and an increased incidence of abortion. No teratogenicity was observed at either dose. After intravenous administration, at doses up to 20 mg/kg, no maternal toxicity was produced and no embryotoxicity or teratogenicity was observed. There are no adequate and well controlled studies in pregnant women. CILOXAN ® (ciprofloxacin ophthalmic ointment) 0.3% should be used during pregnancy only if the potential benefit justifies the potential risk to the fetus.']}]}
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Doxycycline', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Doxycycline)+openfda.generic_name:(DOXYCYCLINE))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 181}, 'results': [{'openfda.brand_name': ['CILOXAN'], 'openfda.generic_name': ['CIPROFLOXACIN HYDROCHLORIDE'], 'pregnancy': ['Pregnancy: Reproduction studies have been performed in rats and mice at doses up to six times the usual daily human oral dose and have revealed no evidence of impaired fertility or harm to the fetus due to ciprofloxacin. In rabbits, as with most antimicrobial agents, ciprofloxacin (30 and 100 mg/kg orally) produced gastrointestinal disturbances resulting in maternal weight loss and an increased incidence of abortion. No teratogenicity was observed at either dose. After intravenous administration, at doses up to 20 mg/kg, no maternal toxicity was produced and no embryotoxicity or teratogenicity was observed. There are no adequate and well controlled studies in pregnant women. CILOXAN ® (ciprofloxacin ophthalmic ointment) 0.3% should be used during pregnancy only if the potential benefit justifies the potential risk to the fetus.']}]}
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Doxycycline', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Doxycycline)+openfda.generic_name:(DOXYCYCLINE))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 146}, 'results': [{'openfda.brand_name': ['doxycycline'], 'openfda.generic_name': ['DOXYCYCLINE'], 'pregnancy': ['Pregnancy: Teratogenic Effects There are no adequate and well-controlled studies on the use of doxycycline in pregnant women. The vast majority of reported experience with doxycycline during human pregnancy is short-term, first trimester exposure. There are no human data available to assess the effects of long-term therapy of doxycycline in pregnant women, such as that proposed for treatment of anthrax exposure. An expert review of published data on experiences with doxycycline use during pregnancy by TERIS-the Teratogen Information System-concluded that therapeutic doses during pregnancy are unlikely to pose a substantial teratogenic risk (the quantity and quality of data were assessed as limited to fair), but the data are insufficient to state that there is no risk. 1 A case-control study (18,515 mothers of infants with congenital anomalies and 32,804 mothers of infants with no congenital anomalies) shows a weak but marginally statistically significant association with total malformations and use of doxycycline anytime during pregnancy. Sixty-three (0.19%) of the controls and fifty-six (0.30%) of the cases were treated with doxycycline. This association was not seen when the analysis was confined to maternal treatment during the period of organogenesis (i.e., in the second and third months of gestation) with the exception of a marginal relationship with neural tube defect based on only two exposed cases. 2 A small prospective study of 81 pregnancies describes 43 pregnant women treated for 10 days with doxycycline during early first trimester. All mothers reported their exposed infants were normal at 1 year of age. 3 Nonteratogenic Effects (See WARNINGS .)']}]}
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Nitrofurantoin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Nitrofurantoin)+openfda.generic_name:(NITROFURANTOIN))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 146}, 'results': [{'openfda.brand_name': ['doxycycline'], 'openfda.generic_name': ['DOXYCYCLINE'], 'pregnancy': ['Pregnancy: Teratogenic Effects There are no adequate and well-controlled studies on the use of doxycycline in pregnant women. The vast majority of reported experience with doxycycline during human pregnancy is short-term, first trimester exposure. There are no human data available to assess the effects of long-term therapy of doxycycline in pregnant women, such as that proposed for treatment of anthrax exposure. An expert review of published data on experiences with doxycycline use during pregnancy by TERIS-the Teratogen Information System-concluded that therapeutic doses during pregnancy are unlikely to pose a substantial teratogenic risk (the quantity and quality of data were assessed as limited to fair), but the data are insufficient to state that there is no risk. 1 A case-control study (18,515 mothers of infants with congenital anomalies and 32,804 mothers of infants with no congenital anomalies) shows a weak but marginally statistically significant association with total malformations and use of doxycycline anytime during pregnancy. Sixty-three (0.19%) of the controls and fifty-six (0.30%) of the cases were treated with doxycycline. This association was not seen when the analysis was confined to maternal treatment during the period of organogenesis (i.e., in the second and third months of gestation) with the exception of a marginal relationship with neural tube defect based on only two exposed cases. 2 A small prospective study of 81 pregnancies describes 43 pregnant women treated for 10 days with doxycycline during early first trimester. All mothers reported their exposed infants were normal at 1 year of age. 3 Nonteratogenic Effects (See WARNINGS .)']}]}
Tool Call: {'name': 'FDA_get_pregnancy_effects_info_by_drug_name', 'arguments': {'drug_name': 'Nitrofurantoin', 'limit': 1}}
https://api.fda.gov/drug/label.json?limit=1&search=(openfda.brand_name:(Nitrofurantoin)+openfda.generic_name:(NITROFURANTOIN))+AND+(_exists_:pregnancy)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 76}, 'results': [{'openfda.brand_name': ['Nitrofurantoin'], 'openfda.generic_name': ['NITROFURANTOIN'], 'pregnancy': ['8.1 Pregnancy Risk Summary Nitrofurantoin is contraindicated in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia in the infant (see Clinical Considerations). Published epidemiological studies, including cohort studies and case control studies, have reported inconsistent findings related to nitrofurantoin use during the first trimester and risk of major birth defects. These studies cannot definitively establish the presence or absence of risk due to several methodological limitations. The limited number of epidemiological studies available have not identified drug-associated risks of major birth defects, miscarriage or other adverse maternal or fetal outcomes. In animal reproduction studies, no fetotoxicity was observed when nitrofurantoin was administered orally to pregnant rats and rabbits, during organogenesis, at up to 6 times the recommended human dose (see Data ). The background risk of major birth defects and miscarriage for the indicated population is unknown. All pregnancies have a background risk of birth defect, loss, or other adverse outcomes. In the U.S. general population, the estimated background risk of major birth defects and miscarriage in clinically recognized pregnancies is 2% to 4% and 15% to 20%, respectively. Clinical Considerations Fetal/Neonatal Adverse Reactions Nitrofurantoin is not recommended in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia due to immature erythrocyte enzyme systems (glutathione instability) [see Contraindications (4) and Warnings and Precautions (5.4)]. Data Animal Data Several reproduction studies have been performed in rabbits and rats at doses up to six times the human dose and have revealed no harm to the fetus due to nitrofurantoin. In a single published study conducted in mice at 68 times the human dose (based on mg/kg administered to the dam), growth retardation and a low incidence of minor and common malformations were observed. However, at 25 times the human dose, fetal malformations were not observed. Nitrofurantoin has been shown in one published transplacental carcinogenicity study to induce lung papillary adenomas in the F1 generation mice at doses 19 times the human dose on a mg/kg basis. The relationship of this finding to potential human carcinogenesis is presently unknown.']}]}
Summarized Tool Result:
Tool Call Result: {'meta': {'skip': 0, 'limit': 1, 'total': 76}, 'results': [{'openfda.brand_name': ['Nitrofurantoin'], 'openfda.generic_name': ['NITROFURANTOIN'], 'pregnancy': ['8.1 Pregnancy Risk Summary Nitrofurantoin is contraindicated in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia in the infant (see Clinical Considerations). Published epidemiological studies, including cohort studies and case control studies, have reported inconsistent findings related to nitrofurantoin use during the first trimester and risk of major birth defects. These studies cannot definitively establish the presence or absence of risk due to several methodological limitations. The limited number of epidemiological studies available have not identified drug-associated risks of major birth defects, miscarriage or other adverse maternal or fetal outcomes. In animal reproduction studies, no fetotoxicity was observed when nitrofurantoin was administered orally to pregnant rats and rabbits, during organogenesis, at up to 6 times the recommended human dose (see Data ). The background risk of major birth defects and miscarriage for the indicated population is unknown. All pregnancies have a background risk of birth defect, loss, or other adverse outcomes. In the U.S. general population, the estimated background risk of major birth defects and miscarriage in clinically recognized pregnancies is 2% to 4% and 15% to 20%, respectively. Clinical Considerations Fetal/Neonatal Adverse Reactions Nitrofurantoin is not recommended in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia due to immature erythrocyte enzyme systems (glutathione instability) [see Contraindications (4) and Warnings and Precautions (5.4)]. Data Animal Data Several reproduction studies have been performed in rabbits and rats at doses up to six times the human dose and have revealed no harm to the fetus due to nitrofurantoin. In a single published study conducted in mice at 68 times the human dose (based on mg/kg administered to the dam), growth retardation and a low incidence of minor and common malformations were observed. However, at 25 times the human dose, fetal malformations were not observed. Nitrofurantoin has been shown in one published transplacental carcinogenicity study to induce lung papillary adenomas in the F1 generation mice at doses 19 times the human dose on a mg/kg basis. The relationship of this finding to potential human carcinogenesis is presently unknown.']}]}
Summarized Tool Result:

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Ceftriaxone and Ciprofloxacin are considered safe for use during pregnancy with no evidence of harm to the fetus in animal studies, while Doxycycline has potential risks and Nitrofurantoin is contraindicated at term due to hemolytic anemia.

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Based on the information retrieved and the specific needs of the patient experiencing burning upon urination during pregnancy at 22 weeks gestation with no costovertebral angle tenderness and no symptoms of pyelonephritis or sepsis (such as fever or chills), I need to determine the best treatment option. The antibiotics should be safe for use during pregnancy and effective for treating urinary tract infections. I will now analyze the options based on the safety and efficacy profiles of each antibiotic.

[FinalAnswer] Ceftriaxone is the best treatment option for this 23-year-old pregnant woman at 22 weeks gestation experiencing burning upon urination. Ceftriaxone is effective for treating urinary tract infections and is considered safe for use during pregnancy. Animal studies have shown no evidence of harm to the fetus with Ceftriaxone. While Ampicillin and Ciprofloxacin also have no evidence of harm to the fetus in animal studies and are considered safe for use during pregnancy when clearly needed (Ampicillin) or only if the potential benefit justifies the potential risk to the fetus (Ciprofloxacin), Ceftriaxone is specifically indicated for urinary tract infections and is generally preferred in pregnant women. Doxycycline has potential risks and Nitrofurantoin is contraindicated at term due to potential hemolytic anemia. [TOOL_CALLS][{"name": "Finish", "arguments": {}}]
Tool Call: {'name': 'Finish', 'arguments': {}}
=======================================================================

' Ceftriaxone is the best treatment option for this 23-year-old pregnant woman at 22 weeks gestation experiencing burning upon urination. Ceftriaxone is effective for treating urinary tract infections and is considered safe for use during pregnancy. Animal studies have shown no evidence of harm to the fetus with Ceftriaxone. While Ampicillin and Ciprofloxacin also have no evidence of harm to the fetus in animal studies and are considered safe for use during pregnancy when clearly needed (Ampicillin) or only if the potential benefit justifies the potential risk to the fetus (Ciprofloxacin), Ceftriaxone is specifically indicated for urinary tract infections and is generally preferred in pregnant women. Doxycycline has potential risks and Nitrofurantoin is contraindicated at term due to potential hemolytic anemia.'

In [ ]:
# question = "Question: A 3-month-old baby died suddenly at night while asleep. His mother noticed that he had died only after she awoke in the morning. No cause of death was determined based on the autopsy. Which of the following precautions could have prevented the death of the baby?\nOptions: Placing the infant in a supine position on a firm mattress while sleeping / Routine postnatal electrocardiogram (ECG) / Keeping the infant covered and maintaining a high room temperature / Application of a device to maintain the sleeping position / Avoiding pacifier use during sleep"

question = " A mother brings her 3-week-old infant to the pediatrician's office because she is concerned about his feeding habits. He was born without complications and has not had any medical problems up until this time. However, for the past 4 days, he has been fussy, is regurgitating all of his feeds, and his vomit is yellow in color. On physical exam, the child's abdomen is minimally distended but no other abnormalities are appreciated. Which of the following embryologic errors could account for this presentation?\nOptions: Abnormal migration of ventral pancreatic bud / Complete failure of proximal duodenum to recanalize / Error in neural crest cell migration / Abnormal hypertrophy of the pylorus / Failure of lateral body folds to move ventrally and fuse in the midling"

response = agent.run_multistep_agent(
    question,
    temperature=0.3,
    max_new_tokens=1024,
    max_token=90240,
    call_agent=multiagent,
    max_round=max_round)


print("=======================================================================")
response

WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

' The symptoms described, such as regurgitation and yellow vomit, suggest a possible obstruction in the gastrointestinal tract. Among the options provided, \'Abnormal migration of ventral pancreatic bud\' is the most likely embryologic error that could account for this presentation. This is because an abnormal migration of the ventral pancreatic bud can lead to an obstruction in the duodenum, causing regurgitation and yellow vomit. [TOOL_CALLS][{"name": "Finish", "arguments": {}}]'

:

## Add tool call, and tool call result in the DB

In [2]:
import pandas as pd
import json
from tqdm import tqdm

data_path = "datasets/MedInstQA/MedQa_train.json"

data = []
with open(data_path, 'r') as f:
    for line in f:
        data.append(json.loads(line.strip()))

df = pd.DataFrame(data)
print(f"Loaded {len(df)} samples")
print(f"Columns: {df.columns.tolist()}")
df.head()

test_df = df.head(2)

Loaded 10178 samples
Columns: ['instruction', 'input', 'output']

In [6]:
# Show full input text (not truncated)
pd.set_option('display.max_colwidth', None)
df.head(20)

,instruction,input,output
0,"Given a question, select the correct answer from the provided options.","Question: A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ago and has been worsening despite drinking more water and taking cranberry extract. She otherwise feels well and is followed by a doctor for her pregnancy. Her temperature is 97.7°F (36.5°C), blood pressure is 122/77 mmHg, pulse is 80/min, respirations are 19/min, and oxygen saturation is 98% on room air. Physical exam is notable for an absence of costovertebral angle tenderness and a gravid uterus. Which of the following is the best treatment for this patient?\nOptions: Ampicillin / Ceftriaxone / Ciprofloxacin / Doxycycline / Nitrofurantoin",Nitrofurantoin
1,"Given a question, select the correct answer from the provided options.",Question: A 3-month-old baby died suddenly at night while asleep. His mother noticed that he had died only after she awoke in the morning. No cause of death was determined based on the autopsy. Which of the following precautions could have prevented the death of the baby?\nOptions: Placing the infant in a supine position on a firm mattress while sleeping / Routine postnatal electrocardiogram (ECG) / Keeping the infant covered and maintaining a high room temperature / Application of a device to maintain the sleeping position / Avoiding pacifier use during sleep,Placing the infant in a supine position on a firm mattress while sleeping
2,"Given a question, select the correct answer from the provided options.","Question: A mother brings her 3-week-old infant to the pediatrician's office because she is concerned about his feeding habits. He was born without complications and has not had any medical problems up until this time. However, for the past 4 days, he has been fussy, is regurgitating all of his feeds, and his vomit is yellow in color. On physical exam, the child's abdomen is minimally distended but no other abnormalities are appreciated. Which of the following embryologic errors could account for this presentation?\nOptions: Abnormal migration of ventral pancreatic bud / Complete failure of proximal duodenum to recanalize / Error in neural crest cell migration / Abnormal hypertrophy of the pylorus / Failure of lateral body folds to move ventrally and fuse in the midline",Abnormal migration of ventral pancreatic bud
3,"Given a question, select the correct answer from the provided options.","Question: A pulmonary autopsy specimen from a 58-year-old woman who died of acute hypoxic respiratory failure was examined. She had recently undergone surgery for a fractured femur 3 months ago. Initial hospital course was uncomplicated, and she was discharged to a rehab facility in good health. Shortly after discharge home from rehab, she developed sudden shortness of breath and had cardiac arrest. Resuscitation was unsuccessful. On histological examination of lung tissue, fibrous connective tissue around the lumen of the pulmonary artery is observed. Which of the following is the most likely pathogenesis for the present findings?\nOptions: Thromboembolism / Pulmonary ischemia / Pulmonary hypertension / Pulmonary passive congestion / Pulmonary hemorrhage",Thromboembolism
4,"Given a question, select the correct answer from the provided options.","Question: A 20-year-old woman presents with menorrhagia for the past several years. She says that her menses “have always been heavy”, and she has experienced easy bruising for as long as she can remember. Family history is significant for her mother, who had similar problems with bruising easily. The patient's vital signs include: heart rate 98/min, respiratory rate 14/min, temperature 36.1°C (96.9°F), and blood pressure 110/87 mm Hg. Physical examination is unremarkable. Laboratory tests show the following: platelet count 200,000/mm3, PT 12 seconds, and PTT 43 seconds. Which of the following is the most likely cause of this patient’s symptoms?\nOptions: Factor V Leiden / Hemophilia A / Lupus anticoagulant / Protein C deficiency / Von Willebrand disease",Von Willebrand disease
5,"Given a question, select the correct answer from the provided options.","Question: A 40-year-old zookeeper presents to the emergency department complaining of severe abdominal pain that radiates to her back, and nausea. The pain started 2 days ago and slowly increased until she could not tolerate it any longer. Past medical history is significant for hypertension and hypothyroidism. Additionally, she reports that she was recently stung by one of the zoo’s smaller scorpions, but did not seek medical treatment. She takes aspirin, levothyroxine, oral contraceptive pills, and a multivitamin daily. Family history is noncontributory. Today, her blood pressure is 108/58 mm Hg, heart rate is 99/min, respiratory rate is 21/min, and temperature is 37.0°C (98.6°F). On physical exam, she is a well-developed, obese female that looks unwell. Her heart has a regular rate and rhythm. Radial pulses are weak but symmetric. Her lungs are clear to auscultation bilaterally. Her lateral left ankle is swollen, erythematous, and painful to palpate. An abdominal CT is consistent with acute pancreatitis. Which of the following is the most likely etiology for this patient’s disease?\nOptions: Aspirin / Oral contraceptive pills / Scorpion sting / Hypothyroidism / Obesity",Scorpion sting
6,"Given a question, select the correct answer from the provided options.","Question: A 25-year-old primigravida presents to her physician for a routine prenatal visit. She is at 34 weeks gestation, as confirmed by an ultrasound examination. She has no complaints, but notes that the new shoes she bought 2 weeks ago do not fit anymore. The course of her pregnancy has been uneventful and she has been compliant with the recommended prenatal care. Her medical history is unremarkable. She has a 15-pound weight gain since the last visit 3 weeks ago. Her vital signs are as follows: blood pressure, 148/90 mm Hg; heart rate, 88/min; respiratory rate, 16/min; and temperature, 36.6℃ (97.9℉). The blood pressure on repeat assessment 4 hours later is 151/90 mm Hg. The fetal heart rate is 151/min. The physical examination is significant for 2+ pitting edema of the lower extremity. Which of the following tests o should confirm the probable condition of this patient?\nOptions: Bilirubin assessment / Coagulation studies / Hematocrit assessment / Leukocyte count with differential / 24-hour urine protein",24-hour urine protein
7,"Given a question, select the correct answer from the provided options.",Question: A 3900-g (8.6-lb) male infant is delivered at 39 weeks' gestation via spontaneous vaginal delivery. Pregnancy and delivery were uncomplicated but a prenatal ultrasound at 20 weeks showed a defect in the pleuroperitoneal membrane. Further evaluation of this patient is most likely to show which of the following findings?\nOptions: Gastric fundus in the thorax / Pancreatic ring around the duodenum / Small and cystic kidneys / Hypertrophy of the gastric pylorus / Large bowel in the inguinal canal,Gastric fundus in the thorax
8,"Given a question, select the correct answer from the provided options.","Question: A 62-year-old woman presents for a regular check-up. She complains of lightheadedness and palpitations which occur episodically. Past medical history is significant for a myocardial infarction 6 months ago and NYHA class II chronic heart failure. She also was diagnosed with grade I arterial hypertension 4 years ago. Current medications are aspirin 81 mg, atorvastatin 10 mg, enalapril 10 mg, and metoprolol 200 mg daily. Her vital signs are a blood pressure of 135/90 mm Hg, a heart rate of 125/min, a respiratory rate of 14/min, and a temperature of 36.5°C (97.7°F). Cardiopulmonary examination is significant for irregular heart rhythm and decreased S1 intensity. ECG is obtained and is shown in the picture (see image). Echocardiography shows a left ventricular ejection fraction of 39%. Which of the following drugs is the best choice for rate control in this patient?\nOptions: Atenolol / Verapamil / Diltiazem / Propafenone / Digoxin",Digoxin
9,"Given a question, select the correct answer from the provided options.",Question: A 35-year-old male presents to his primary care physician with complaints of seasonal allergies. He has been using intranasal vasoconstrictors several times per day for several weeks. What is a likely sequela of the chronic use of topical nasal decongestants?\nOptions: Epistaxis / Hypertension / Permanent loss of smell / Persistent nasal crusting / Persistent congestion,Persistent congestion
10,"Given a question, select the correct answer from the provided options.","Question: A 46-year-old woman comes to the physician because of a 2-week history of diplopia and ocular pain when reading the newspaper. She also has a 3-month history of amenorrhea, hot flashes, and increased sweating. She reports that she has been overweight all her adult life and is happy to have lost 6.8-kg (15-lb) of weight in the past 2 months. Her pulse is 110/min, and blood pressure is 148/98 mm Hg. Physical examination shows moist palms and a nontender thyroid gland that is enlarged to two times its normal size. Ophthalmologic examination shows prominence of the globes of the eyes, bilateral lid retraction, conjunctival injection, and an inability to converge the eyes. There is no pain on movement of the extraocular muscles. Visual acuity is 20/20 bilaterally. Neurologic examination shows a fine resting tremor of the hands. Deep tendon reflexes are 3+ with a shortened relaxation phase. Which of the following is the most likely cause of this patient's ocular complaints?\nOptions: Granulomatous inflammation of the cavernous sinus / Abnormal communication between the cavernous sinus and the internal carotid artery / Glycosaminoglycan accumulation in the orbit / Bacterial infection of the orbital contents / Sympathetic hyperactivity of levator palpebrae superioris\n""",Glycosaminoglycan accumulation in the orbit
11,"Given a question, select the correct answer from the provided options.","Question: A 1-year-old boy presents to the emergency department with weakness and a change in his behavior. His parents state that they first noticed the change in his behavior this morning and it has been getting worse. They noticed the patient was initially weak in his upper body and arms, but now he won’t move his legs with as much strength or vigor as he used to. Physical exam is notable for bilateral ptosis with a sluggish pupillary response, a very weak sucking and gag reflex, and shallow respirations. The patient is currently drooling and his diaper is dry. The parents state he has not had a bowel movement in over 1 day. Which of the following is the pathophysiology of this patient’s condition?\nOptions: Antibodies against postsynaptic nicotinic cholinergic ion channels / Autoantibodies against the presynaptic voltage-gated calcium channels / Autoimmune demyelination of peripheral nerves / Blockade of presynaptic acetylcholine release at the neuromuscular junction / Lower motor neuron destruction in the anterior horn",Blockade of presynaptic acetylcholine release at the neuromuscular junction
12,"Given a question, select the correct answer from the provided options.","Question: A 9-month-old female is brought to the emergency department after experiencing a seizure. She was born at home and was normal at birth according to her parents. Since then, they have noticed that she does not appear to be achieving developmental milestones as quickly as her siblings, and often appears lethargic. Physical exam reveals microcephaly, very light pigmentation (as compared to her family), and a ""musty"" body odor. The varied manifestations of this disease can most likely be attributed to which of the following genetic principles?\nOptions: Anticipation / Incomplete penetrance / Multiple gene mutations / Pleiotropy / Variable expressivity",Pleiotropy
13,"Given a question, select the correct answer from the provided options.","Question: A 23-year-old man comes to the physician for evaluation of decreased hearing, dizziness, and ringing in his right ear for the past 6 months. Physical examination shows multiple soft, yellow plaques and papules on his arms, chest, and back. There is sensorineural hearing loss and weakness of facial muscles bilaterally. His gait is unsteady. An MRI of the brain shows a 3-cm mass near the right internal auditory meatus and a 2-cm mass at the left cerebellopontine angle. The abnormal cells in these masses are most likely derived from which of the following embryological structures?\nOptions: Neural tube / Surface ectoderm / Neural crest / Notochord / Mesoderm",Neural crest
14,"Given a question, select the correct answer from the provided options.","Question: A 62-year-old woman comes to the physician because of coughing and fatigue during the past 2 years. In the morning, the cough is productive of white phlegm. She becomes short of breath walking up a flight of stairs. She has hypertension and hyperlipidemia. She has recently retired from working as a nurse at a homeless shelter. She has smoked 1 pack of cigarettes daily for 40 years. Current medications include ramipril and fenofibrate. Her temperature is 36.5°C (97.7°F), respirations are 24/min, pulse is 85/min, and blood pressure is 140/90 mm Hg. Scattered wheezing and rhonchi are heard throughout both lung fields. There are no murmurs, rubs, or gallops but heart sounds are distant. Which of the following is the most likely underlying cause of this patient's symptoms?\nOptions: Chronic decrease in pulmonary compliance / Local accumulation of kinins / Mycobacterial invasion of pulmonary parenchyma / Progressive obstruction of expiratory airflow / Incremental loss of functional residual capacity\n""",Progressive obstruction of expiratory airflow
15,"Given a question, select the correct answer from the provided options.","Question: A 68-year-old man presents to the emergency department with leg pain. He states that the pain started suddenly while he was walking outside. The patient has a past medical history of diabetes, hypertension, obesity, and atrial fibrillation. His temperature is 99.3°F (37.4°C), blood pressure is 152/98 mmHg, pulse is 97/min, respirations are 15/min, and oxygen saturation is 99% on room air. Physical exam is notable for a cold and pale left leg. The patient’s sensation is markedly diminished in the left leg when compared to the right, and his muscle strength is 1/5 in his left leg. Which of the following is the best next step in management?\nOptions: CT angiogram / Graded exercise and aspirin / Heparin drip / Surgical thrombectomy / Tissue plasminogen activator",Heparin drip
16,"Given a question, select the correct answer from the provided options.","Question: A 76-year-old African American man presents to his primary care provider complaining of urinary frequency. He wakes up 3-4 times per night to urinate while he previously only had to wake up once per night. He also complains of post-void dribbling and difficulty initiating a stream of urine. He denies any difficulty maintaining an erection. His past medical history is notable for non-alcoholic fatty liver disease, hypertension, hyperlipidemia, and gout. He takes aspirin, atorvastatin, enalapril, and allopurinol. His family history is notable for prostate cancer in his father and lung cancer in his mother. He has a 15-pack-year smoking history and drinks alcohol socially. On digital rectal exam, his prostate is enlarged, smooth, and non-tender. Which of the following medications is indicated in this patient?\nOptions: Clonidine / Hydrochlorothiazide / Midodrine / Oxybutynin / Tamsulosin",Tamsulosin
17,"Given a question, select the correct answer from the provided options.","Question: A 68-year-old man comes to the physician because of recurrent episodes of nausea and abdominal discomfort for the past 4 months. The discomfort is located in the upper abdomen and sometimes occurs after eating, especially after a big meal. He has tried to go for a walk after dinner to help with digestion, but his complaints have only increased. For the past 3 weeks he has also had symptoms while climbing the stairs to his apartment. He has type 2 diabetes mellitus, hypertension, and stage 2 peripheral arterial disease. He has smoked one pack of cigarettes daily for the past 45 years. He drinks one to two beers daily and occasionally more on weekends. His current medications include metformin, enalapril, and aspirin. He is 168 cm (5 ft 6 in) tall and weighs 126 kg (278 lb); BMI is 45 kg/m2. His temperature is 36.4°C (97.5°F), pulse is 78/min, and blood pressure is 148/86 mm Hg. On physical examination, the abdomen is soft and nontender with no organomegaly. Foot pulses are absent bilaterally. An ECG shows no abnormalities. Which of the following is the most appropriate next step in diagnosis?\nOptions: Esophagogastroduodenoscopy / CT scan of the abdomen / Hydrogen breath test / Cardiac stress test / Abdominal ultrasonography of the right upper quadrant",Cardiac stress test
18,"Given a question, select the correct answer from the provided options.","Question: A 27-year-old female presents to general medical clinic for a routine checkup. She has a genetic disease marked by a mutation in a chloride transporter. She has a history of chronic bronchitis. She has a brother with a similar history of infections as well as infertility. Which of the following is most likely true regarding a potential vitamin deficiency complication secondary to this patient's chronic illness?\nOptions: It may result in connective tissue defects / It may result in corneal vascularization / It may result in the triad of confusion, ophthalmoplegia, and ataxia / It may be exacerbated by excessive ingestion of raw eggs / It may manifest itself as a prolonged PT",It may manifest itself as a prolonged PT
19,"Given a question, select the correct answer from the provided options.",Question: A previously healthy 36-year-old man comes to the physician for a yellow discoloration of his skin and dark-colored urine for 2 weeks. He does not drink any alcohol. Physical examination shows jaundice. Abdominal and neurologic examinations show no abnormalities. Serum studies show increased levels of alanine aminotransferase (ALT) and aspartate aminotransferase (AST). A liver biopsy is performed and a photomicrograph after periodic acid-Schiff-staining is shown. Which of the following is the most likely additional finding in this patient?\nOptions: Tropheryma whipplei-specific RNA on PCR / Bullous changes of the lung bases on chest CT / Beading of intra- and extrahepatic bile ducts on ERCP / Myocardial iron deposition on cardiovascular MRI / Dark corneal ring on slit-lamp examination,Bullous changes of the lung bases on chest CT

In [ ]:
# Run TxAgent on each row to get tool calls with arguments AND results
# Capture stdout to extract tool call results that are only printed
import json
import sys
import io
import re

def parse_tool_calls_from_output(output_text):
    """Parse tool calls and results from TxAgent's printed output."""
    # Remove ANSI color codes
    ansi_escape = re.compile(r'\x1b\[[0-9;]*m')
    clean_text = ansi_escape.sub('', output_text)
    
    tool_calls_with_results = []
    
    # Split by "Tool Call:" to get individual tool call sections
    # Pattern: Tool Call: {dict} ... Tool Call Result: {result}
    sections = clean_text.split('Tool Call:')
    
    for section in sections[1:]:  # Skip first empty section
        try:
            # Find the tool call dict (ends at first newline or "Tool Call Result:")
            # The dict format is: {'name': '...', 'arguments': {...}}
            
            # Extract tool name and arguments using regex
            name_match = re.search(r"'name':\s*'([^']+)'", section)
            args_match = re.search(r"'arguments':\s*(\{[^}]+\})", section)
            
            if not name_match:
                continue
                
            tool_name = name_match.group(1)
            
            # Skip Finish and Tool_RAG
            if tool_name in ['Finish', 'Tool_RAG']:
                continue
            
            # Parse arguments
            arguments = None
            if args_match:
                try:
                    # Convert single quotes to double quotes for JSON
                    args_str = args_match.group(1).replace("'", '"')
                    arguments = json.loads(args_str)
                except:
                    arguments = args_match.group(1)
            
            # Find the result - it comes after "Tool Call Result:"
            result_match = re.search(r'Tool Call Result:\s*(.+?)(?=Tool Call:|Summarized Tool Result:|$)', section, re.DOTALL)
            
            result = None
            if result_match:
                result_str = result_match.group(1).strip()
                # Truncate very long results but try to parse JSON first
                if result_str.startswith('{') or result_str.startswith('['):
                    try:
                        # Try to parse as JSON
                        result = json.loads(result_str.split('\n')[0])  # Just first line if multiline
                    except:
                        # Truncate long results
                        result = result_str[:1000] + '...' if len(result_str) > 1000 else result_str
                else:
                    result = result_str[:1000] + '...' if len(result_str) > 1000 else result_str
            
            tool_calls_with_results.append({
                'name': tool_name,
                'arguments': arguments,
                'result': result
            })
            
        except Exception as e:
            continue
    
    return tool_calls_with_results

results = []

for idx, row in tqdm(df.iterrows(), total=len(df), desc="Running TxAgent inference"):
    query = row['input']
    
    try:
        # Capture stdout to get tool call results
        captured_output = io.StringIO()
        sys.stdout = captured_output
        
        # Run TxAgent to get tool calls
        response = agent.run_multistep_agent(
            query,
            temperature=0.3,
            max_new_tokens=1024,
            max_token=90240,
            call_agent=multiagent,
            max_round=max_round
        )
        
        # Restore stdout
        sys.stdout = sys.__stdout__
        output_text = captured_output.getvalue()
        
        # Parse tool calls and results from captured output
        tool_calls_with_results = parse_tool_calls_from_output(output_text)
        
        results.append({
            'index': idx,
            'instruction': row.get('instruction', ''),
            'input': query,
            'output': row['output'],
            'tool_calls': tool_calls_with_results,
            'final_response': response
        })
        
        # Print progress
        print(f"\n--- Sample {idx} ---")
        print(f"Query: {query[:100]}...")
        print(f"Tool Calls Captured: {len(tool_calls_with_results)}")
        for tc in tool_calls_with_results[:3]:
            print(f"  - {tc.get('name')}: {str(tc.get('arguments'))[:60]}...")
            if tc.get('result'):
                result_preview = str(tc.get('result'))[:80]
                print(f"    Result: {result_preview}...")
        
    except Exception as e:
        sys.stdout = sys.__stdout__  # Restore stdout on error
        results.append({
            'index': idx,
            'instruction': row.get('instruction', ''),
            'input': query,
            'output': row['output'],
            'tool_calls': None,
            'final_response': None,
            'error': str(e)
        })
        print(f"Error on sample {idx}: {e}")

results_df = pd.DataFrame(results)
print(f"\nCompleted inference on {len(results_df)} samples")
print(f"Total tool calls captured: {sum(len(tc) if tc else 0 for tc in results_df['tool_calls'])}")
results_df.head()

Running TxAgent inference:   0%|          | 0/2 [00:00<?, ?it/s]WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Running TxAgent inference:  50%|█████     | 1/2 [01:28<01:28, 88.92s/it]WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.
WARNING:tooluniverse:The 'get_one_tool_by_one_name' method is deprecated and will be removed in a future version. Please use 'tool_specification' instead.

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

ERROR:tooluniverse.AgenticTool:Tool 'UnifiedToolGenerator' is not available due to initialization error: Failed to initialize GEMINI model gemini-2.0-flash: GEMINI_API_KEY not found
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tooluniverse/compose_tool.py", line 273, in run
    return self._execute_from_file(arguments, stream_callback)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tooluniverse/compose_tool.py", line 370, in _execute_from_file
    return compose_func(**{k: v for k, v in call_args.items() if k in params})
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tooluniverse/compose_scripts/tool_discover.py", line 2107, in compose
    tool_config = _generate_tool_with_xml(
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tooluniverse/compose_scripts/tool_discover.py", line 445, in _generate_tool_with_xml
    print(result["result"])
KeyError: 'result'
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tooluniverse/compose_tool.py", line 273, in run
    return self._execute_from_file(arguments, stream_callback)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tooluniverse/compose_tool.py", line 370, in _execute_from_file
    return compose_func(**{k: v for k, v in call_args.items() if k in params})
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tooluniverse/compose_scripts/tool_discover.py", line 2107, in compose
    tool_config = _generate_tool_with_xml(
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tooluniverse/compose_scripts/tool_discover.py", line 445, in _generate_tool_with_xml
    print(result["result"])
KeyError: 'result'

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Running TxAgent inference: 100%|██████████| 2/2 [02:06<00:00, 63.44s/it]

   index  \
0      0
1      1

                                                              instruction  \
0  Given a question, select the correct answer from the provided options.
1  Given a question, select the correct answer from the provided options.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 input  \
0  Question: A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ago and has been worsening despite drinking more water and taking cranberry extract. She otherwise feels well and is followed by a doctor for her pregnancy. Her temperature is 97.7°F (36.5°C), blood pressure is 122/77 mmHg, pulse is 80/min, respirations are 19/min, and oxygen saturation is 98% on room air. Physical exam is notable for an absence of costovertebral angle tenderness and a gravid uterus. Which of the following is the best treatment for this patient?\nOptions: Ampicillin / Ceftriaxone / Ciprofloxacin / Doxycycline / Nitrofurantoin
1                                                                                                               Question: A 3-month-old baby died suddenly at night while asleep. His mother noticed that he had died only after she awoke in the morning. No cause of death was determined based on the autopsy. Which of the following precautions could have prevented the death of the baby?\nOptions: Placing the infant in a supine position on a firm mattress while sleeping / Routine postnatal electrocardiogram (ECG) / Keeping the infant covered and maintaining a high room temperature / Application of a device to maintain the sleeping position / Avoiding pacifier use during sleep

                                                                      output  \
0                                                             Nitrofurantoin
1  Placing the infant in a supine position on a firm mattress while sleeping


In [10]:
results_df['tool_calls'][0]

[{'name': 'FDA_get_population_use_info_by_drug_name',
  'arguments': {'drug_name': 'Ampicillin', 'limit': 5},
  'result': 'None'},
 {'name': 'FDA_get_population_use_info_by_drug_name',
  'arguments': {'drug_name': 'Ceftriaxone', 'limit': 5},
  'result': "{'meta': {'skip': 0, 'limit': 5, 'total': 2}, 'results': [{'openfda.brand_name': ['Ceftriaxone'], 'openfda.generic_name': ['CEFTRIAXONE SODIUM'], 'use_in_specific_populations': ['8 USE IN SPECIFIC POPULATIONS Hepatic impairment: Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day. ( 5.7 ) Renal Impairment: This formulation of Ceftriaxone for Injection USP – Pharmacy Bulk Package bag, SmartPak ® should not be used in renally impaired patients who require less than the 1 gram dose of ceftriaxone. Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day. ( 5.7 ) Pediatric Patients: This formulation of Ceftriaxone for Injection USP – Pharmacy Bulk Package bag, SmartPak ® should not be used in pediatric patients who require less than the 1 gram adult dose of ceftriaxone. ( 2.2 , 8.4 ) 8.1 Pregnancy Pregnancy Category B. Reproductive studies have been performed in mice, rats, and primat..."},
 {'name': 'FDA_get_population_use_info_by_drug_name',
  'arguments': {'drug_name': 'Ciprofloxacin', 'limit': 5},
  'result': "{'meta': {'skip': 0, 'limit': 5, 'total': 174}, 'results': [{'openfda.brand_name': ['ciprofloxacin'], 'openfda.generic_name': ['CIPROFLOXACIN'], 'use_in_specific_populations': ['8 USE IN SPECIFIC POPULATIONS Lactation: Breastfeeding is not recommended during treatment, but a lactating woman may pump and discard breastmilk during treatment and an additional 2 days after the last dose. In patients treated for inhalational anthrax (post exposure), consider the risks and benefits of continuing breastfeeding. ( 8.2 ) See full prescribing information for use in pediatric and geriatric patients ( 8.4 , 8.5 ) 8.1 Pregnancy Risk Summary Prolonged experience with ciprofloxacin in pregnant women over several decades, based on available published information from case reports, case control studies and observational studies on ciprofloxacin administered during pregnancy, have not identified any drug-associated risk of major birth defects, miscarriage or adverse maternal or fetal outcomes (see Data)..."},
 {'name': 'FDA_get_population_use_info_by_drug_name',
  'arguments': {'drug_name': 'Doxycycline', 'limit': 5},
  'result': "{'meta': {'skip': 0, 'limit': 5, 'total': 26}, 'results': [{'openfda.brand_name': ['DOXYCYCLINE HYCLATE'], 'openfda.generic_name': ['DOXYCYCLINE HYCLATE'], 'use_in_specific_populations': ['8 USE IN SPECIFIC POPULATIONS • Tetracycline-class drugs can cause fetal harm when administered to a pregnant woman, but data for doxycycline are limited. ( 5.6 , 8.1 ) • Tetracyclines are excreted in human milk; however, the extent of absorption of doxycycline in the breastfed infant is not known. Doxycycline use during nursing should be avoided if possible. ( 8.3 ) 8.1 Pregnancy Risk Summary There are no adequate and well-controlled studies on the use of doxycycline in pregnant women. The vast majority of reported experience with doxycycline during human pregnancy is short-term, first trimester exposure. There are no human data available to assess the effects of long-term therapy of doxycycline in pregnant women such as that proposed for the treatment of anthrax exposure. An expert review of publis..."},
 {'name': 'FDA_get_population_use_info_by_drug_name',
  'arguments': {'drug_name': 'Nitrofurantoin', 'limit': 5},
  'result': "{'meta': {'skip': 0, 'limit': 5, 'total': 9}, 'results': [{'openfda.brand_name': ['Nitrofurantoin'], 'openfda.generic_name': ['NITROFURANTOIN'], 'use_in_specific_populations': ['8 USE IN SPECIFIC POPULATIONS Lactation: Breastfeeding is not recommended in infants under one month of age or with glucose-6-phosphate dehydrogenase (G6PD) deficiency. (8.2) Pediatric Use: Nitrofurantoin is contraindicated in pediatric patients under one month of age. (8.4) 8.1 Pregnancy Risk Summary Nitrofurantoin is contraindicated in pregnant women at term (38 weeks to 42 weeks gestation), during labor and delivery, or when the onset of labor is imminent because of the possibility of hemolytic anemia in the infant (see Clinical Considerations). Published epidemiological studies, including cohort studies and case control studies, have reported inconsistent findings related to nitrofurantoin use during the first trimester and risk of major birth defects. These studies cannot definitively establish the presenc..."}]

In [ ]:
# Test parsing on existing raw output
if 'results_df' in dir() and len(results_df) > 0 and 'raw_output' in results_df.columns:
    sample_output = results_df['raw_output'][0]
    parsed = parse_tool_calls_from_output(sample_output)
    print(f"Parsed {len(parsed)} tool calls from raw output")
    for i, tc in enumerate(parsed[:5]):
        print(f"\n{i+1}. {tc['name']}")
        print(f"   Args: {tc['arguments']}")
        print(f"   Result: {str(tc.get('result', ''))[:200]}...")
else:
    print("No raw_output available - run the inference cell first")

'\x1b[1;32;40mstart\x1b[0m\nFinish tool is added\nTool_RAG tool is added\n\x1b[92mTo determine the best treatment for the pregnant woman with symptoms of a urinary tract infection, I need to gather information on the indications and safety profiles of the antibiotics listed in the options. Specifically, I need to identify which antibiotics are safe for use during pregnancy and effective against urinary tract infections. I will start by retrieving information on the indications and usage of each antibiotic option. [TOOL_CALLS][{"name": "Tool_RAG", "arguments": {"description": "Get information about the indications and usage of a specific drug based on its name.", "limit": 5}}, {"name": "Tool_RAG", "arguments": {"description": "Get information about the use of a specific drug in pregnant women based on the drug name.", "limit": 5}}]\x1b[0m\n\x1b[94mTool Call:\x1b[0m {\'name\': \'Tool_RAG\', \'arguments\': {\'description\': \'Get information about the indications and usage of a specific drug based on its name.\', \'limit\': 5}}\n\x1b[94mTool Call Result:\x1b[0m [\'FDA_get_pregnancy_effects_info_by_drug_name\', \'FDA_get_population_use_info_by_drug_name\', \'FDA_get_drug_names_by_pregnancy_effects_info\', \'euhealthinfo_search_births\', \'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name\', \'FDA_get_labor_and_delivery_info_by_drug_name\', \'FDA_get_drug_names_by_population_use\', \'odphp_myhealthfinder\', \'FDA_get_risk_info_by_drug_name\', \'FDA_get_drug_name_by_pregnancy_or_breastfeeding_info\']\n\x1b[94mTool Call:\x1b[0m {\'name\': \'Tool_RAG\', \'arguments\': {\'description\': \'Get information about the use of a specific drug in pregnant women based on the drug name.\', \'limit\': 5}}\n\x1b[94mTool Call Result:\x1b[0m [\'FDA_get_pregnancy_effects_info_by_drug_name\', \'FDA_get_population_use_info_by_drug_name\', \'FDA_get_drug_names_by_pregnancy_effects_info\', \'euhealthinfo_search_births\', \'FDA_get_pregnancy_or_breastfeeding_info_by_drug_name\', \'FDA_get_labor_and_delivery_info_by_drug_name\', \'FDA_get_drug_names_by_population_use\', \'odphp_myhealthfinder\', \'FDA_get_risk_info_by_drug_name\', \'FDA_get_drug_name_by_pregnancy_or_breastfeeding_info\']\n\x1b[92mTo determine the best treatment option, I need to evaluate the safety profiles of the antibiotics listed in the options, specifically focusing on their use during pregnancy. I will retrieve information about the use of each antibiotic in pregnant women to identify which are safe and effective. [TOOL_CALLS][{"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Ampicillin", "limit": 5}}, {"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Ceftriaxone", "limit": 5}}, {"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Ciprofloxacin", "limit": 5}}, {"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Doxycycline", "limit": 5}}, {"name": "FDA_get_population_use_info_by_drug_name", "arguments": {"drug_name": "Nitrofurantoin", "limit": 5}}]\x1b[0m\n\x1b[94mTool Call:\x1b[0m {\'name\': \'FDA_get_population_use_info_by_drug_name\', \'arguments\': {\'drug_name\': \'Ampicillin\', \'limit\': 5}}\nhttps://api.fda.gov/drug/label.json?limit=5&search=(openfda.brand_name:(Ampicillin)+openfda.generic_name:(AMPICILLIN))+AND+(_exists_:use_in_specific_populations)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)\nInvalid Query:  {\'code\': \'NOT_FOUND\', \'message\': \'No matches found!\'}\n\x1b[94mTool Call Result:\x1b[0m None\n\x1b[94mTool Call:\x1b[0m {\'name\': \'FDA_get_population_use_info_by_drug_name\', \'arguments\': {\'drug_name\': \'Ceftriaxone\', \'limit\': 5}}\nhttps://api.fda.gov/drug/label.json?limit=5&search=(openfda.brand_name:(Ceftriaxone)+openfda.generic_name:(CEFTRIAXONE))+AND+(_exists_:use_in_specific_populations)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)\n\x1b[94mTool Call Result:\x1b[0m {\'meta\': {\'skip\': 0, \'limit\': 5, \'total\': 2}, \'results\': [{\'openfda.brand_name\': [\'Ceftriaxone\'], \'openfda.generic_name\': [\'CEFTRIAXONE SODIUM\'], \'use_in_specific_populations\': [\'8 USE IN SPECIFIC POPULATIONS Hepatic impairment: Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day. ( 5.7 ) Renal Impairment: This formulation of Ceftriaxone for Injection USP – Pharmacy Bulk Package bag, SmartPak ® should not be used in renally impaired patients who require less than the 1 gram dose of ceftriaxone. Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day. ( 5.7 ) Pediatric Patients: This formulation of Ceftriaxone for Injection USP – Pharmacy Bulk Package bag, SmartPak ® should not be used in pediatric patients who require less than the 1 gram adult dose of ceftriaxone. ( 2.2 , 8.4 ) 8.1 Pregnancy Pregnancy Category B. Reproductive studies have been performed in mice, rats, and primates at intravenous doses of 625, 586, and 84 mg/kg/day, respectively without evidence of embryotoxicity, fetotoxicity, or teratogenicity. These doses are approximately 1.5, 2.8, and 0.8 times the recommended clinical dose of 2 grams/day based on body surface area comparisons. There are, however, no adequate and well-controlled studies in pregnant women. Because animal reproductive studies are not always predictive of human response, this drug should be used during pregnancy only if clearly needed. Ceftriaxone was tested in a Segment III (pre-postnatal) study in rats at intravenous doses of up to 586 mg/kg/day approximately 2.8 times (mg/m 2 comparison) the recommended daily dose of 2 grams/day. No adverse effects were noted on various reproductive parameters during gestation and lactation, including postnatal growth, functional behavior, and reproductive ability of the offspring. 8.3 Nursing Mothers Ceftriaxone is excreted in human breast milk. Caution should be exercised when Ceftriaxone for Injection is administered to a nursing woman. 8.4 Pediatric Use Ceftriaxone for Injection USP, Pharmacy Bulk Package bag, SmartPak ® should not be used in pediatric patients who require less than the 1 gram dose of ceftriaxone. To prevent unintentional overdose, this product should not be used in pediatric patients who require less than the adult 1 gram dose of ceftriaxone. 8.5 Geriatric Use Of the total number of subjects in clinical studies of ceftriaxone sodium, 32% were 60 and over. No overall differences in safety or effectiveness were observed between these subjects and younger subjects, and other reported clinical experience has not identified differences in responses between the elderly and younger patients, but greater sensitivity of some older individuals cannot be ruled out. Ceftriaxone is known to be substantially excreted by the kidney, and the risk of adverse reactions to this drug may be greater in patients with impaired renal function. Because elderly patients are more likely to have decreased renal function, care should be taken in dose selection, and it may be useful to monitor renal function. The pharmacokinetics of ceftriaxone were only minimally altered in geriatric patients compared to healthy adult subjects, and dosage adjustments are not necessary for geriatric patients with ceftriaxone dosages up to 2 grams per day [see Clinical Pharmacology (12) ].\']}, {\'openfda.brand_name\': [\'CEFTRIAXONE AND DEXTROSE\'], \'openfda.generic_name\': [\'CEFTRIAXONE\'], \'use_in_specific_populations\': [\'8 USE IN SPECIFIC POPULATIONS Hepatic and renal impairment Patients with both hepatic and renal impairment should not receive more than 2 grams of ceftriaxone per day ( 5.8 ) Pediatric Patients Ceftriaxone for Injection and Dextrose Injection in the DUPLEX® Container is designed to deliver a 1 g or 2 g dose of ceftriaxone. To prevent unintentional overdose, this product should not be used in pediatric patients who require less than the full adult dose of ceftriaxone. ( 2.2 , 8.4 ) 8.1 Pregnancy Risk Summary Available data from published prospective cohort studies, case series, and case reports over several decades with cephalosporin use, including Ceftriaxone, in pregnant women have not established a drug-associated risk of major birth defects, miscarriage, or adverse maternal or fetal outcomes. Ceftriaxone crosses the placenta. In animal reproduction studies, no adverse developmental effects were observed when ceftriaxone was administered to pregnant rats at doses up to approximately 2.8 times the clinical dose of 2 g/day (see Data) . The estimated background risk of major birth defects and miscarriage for the indicated population is unknown. All pregnancies have a background risk of birth defect, loss, or other adverse outcomes. In the U.S. general population, the estimated background risk of major birth defects and miscarriage in clinically recognized pregnancies is 2% to 4% and 15% to 20%, respectively. Data Human Data Published literature shows that ceftriaxone crosses the placenta. While available studies cannot definitively establish the absence of risk, published data from case-control studies and case reports over several decades have not identified an association with cephalosporin use during pregnancy and major birth defects, miscarriage, or other adverse maternal or fetal outcomes. Available studies have methodologic limitations, including small sample size, retrospective data collection, and inconsistent comparator groups. Animal Data Reproductive studies have been performed in mice, rats, and primates at intravenous doses of 625, 586, and 84 mg/kg/day, respectively, without evidence of embryotoxicity, fetotoxicity, or teratogenicity. These doses are approximately 1.5, 2.8, and 0.8 times the clinical dose of 2 g/day based on body surface area comparisons. Ceftriaxone was tested in a Segment III (pre-postnatal) study in rats at intravenous doses of up to 586 mg/kg/day (approximately 2.8 times the clinical dose of 2 g/day based on body surface area comparison). No adverse effects were noted on various reproductive parameters during gestation and lactation, including postnatal growth, functional behavior, and reproductive ability of the offspring. 8.2 Lactation Risk Summary Data from published literature report that ceftriaxone is present in human milk. There are no data on the effects of Ceftriaxone on the breastfed child or on milk production. The developmental and health benefits of breastfeeding should be considered along with the mother’s clinical need for Ceftriaxone for Injection and Dextrose Injection and any potential adverse effects on the breastfed child from Ceftriaxone for Injection and Dextrose Injection or from the mother’s underlying condition. 8.4 Pediatric Use Ceftriaxone for Injection and Dextrose Injection in the DUPLEX® Container is designed to deliver a 1 g or 2 g dose of ceftriaxone. To prevent unintentional overdose, this product should not be used in pediatric patients who require less than the full 1 g or 2 g adult dose of ceftriaxone. 8.5 Geriatric Use Of the total number of subjects in clinical studies of ceftriaxone sodium, 32% were 60 and over. No overall differences in safety or effectiveness were observed between these subjects and younger subjects, and other reported clinical experience has not identified differences in responses between the elderly and younger patients, but greater sensitivity of some older individuals cannot be ruled out. Ceftriaxone is known to be substantially excreted by the kidney, and the risk of adverse reactions to this drug may be greater in patients with impaired renal function. Because elderly patients are more likely to have decreased renal function, care should be taken in dose selection, and it may be useful to monitor renal function. The pharmacokinetics of ceftriaxone were only minimally altered in geriatric patients compared to healthy adult subjects and dosage adjustments are not necessary for geriatric patients with ceftriaxone dosages up to 2 grams per day, provided there is no severe renal and hepatic impairment. [see Clinical Pharmacology (12) ]\']}]}\n\x1b[94mTool Call:\x1b[0m {\'name\': \'FDA_get_population_use_info_by_drug_name\', \'arguments\': {\'drug_name\': \'Ciprofloxacin\', \'limit\': 5}}\nhttps://api.fda.gov/drug/label.json?limit=5&search=(openfda.brand_name:(Ciprofloxacin)+openfda.generic_name:(CIPROFLOXACIN))+AND+(_exists_:use_in_specific_populations)+AND+(_exists_:openfda.brand_name+_exists_:openfda.generic_name)\n\x1b[94mTool Call Result:\x1b[0m {\'meta\': {\'skip\': 0, \'limit\': 5, \'total\': 174}, \'results\': [{\'openfda.brand_name\': [\'ciprofloxacin\'], \'openfda.generic_name\': [\'CIPROFLOXACIN\'], \'use_in_specific_populations\': [\'8 USE IN SPECIFIC POPULATIONS Lactation: Breastfeeding is not recommended during treatment, but a lactating woman may pump and discard breastmilk during treatment and an additional 2 days after the last dose. In patients treated for inhalational anthrax (post exposure), consider the risks and benefits of continuing breastfeeding. ( 8.2 ) See full prescribing information for use in pediatric and geriatric patients ( 8.4 , 8.5 ) 8.1 Pregnancy Risk Summary Prolonged experience with ciprofloxacin in pregnant women over several decades, based on available published information from case reports, case control studies and observational studies on ciprofloxacin administered during pregnancy, have not identified any drug-associated risk of major birth defects, miscarriage or adverse maternal or fetal outcomes (see Data) . Oral administration of ciprofloxacin during organogenesis at doses up to 100 mg/kg to pregnant mice and rats, and up to 30 mg/kg to pregnant rabbits did not cause fetal malformations (see Data). These doses were up to 0.3, 0.6, and 0.4 times the maximum recommended clinical oral dose in mice, rats, and rabbits, respectively, based on body surface area. The estimated background risk of major birth defects and miscarriage for the indicated population is unknown. All pregnancies have a background risk of birth defect, loss, or other adverse outcomes. In the U.S. general population, the estimated background risks of major birth defects and miscarriage in clinically recognized pregnancies is 2 to 4% and 15 to 20%, respectively. Data Human Data While available studies cannot definitively establish the absence of risk, published data from prospective observational studies over several decades have not established an association with ciprofloxacin use during pregnancy and major birth defects, miscarriage, or adverse maternal or fetal outcomes. Available studies have methodological limitations including small sample size and some of them are not specific for ciprofloxacin. A controlled prospective observational study followed 200 women exposed to fluoroquinolones (52.5% exposed to ciprofloxacin and 68% first trimester exposures) during gestation. In utero exposure to fluoroquinolones during embryogenesis was not associated with increased risk of major malformations. The reported rates of major congenital malformations were 2.2% for the fluoroquinolone group and 2.6% for the control group (background incidence of major malformations is 1–5%). Rates of spontaneous abortions, prematurity and low birth weight did not differ between the groups and there were no clinically significant musculoskeletal dysfunctions up to one year of age in the ciprofloxacin exposed children. Another prospective follow-up study reported on 549 pregnancies with fluoroquinolone exposure (93% first trimester exposures). There were 70 ciprofloxacin exposures, all within the first trimester. The malformation rates among live-born babies exposed to ciprofloxacin and to fluoroquinolones overall were both within background incidence ranges. No specific patterns of congenital abnormalities were found. The study did not reveal any clear adverse reactions due to in utero exposure to ciprofloxacin. No differences in the rates of prematurity, spontaneous abortions, or birth weight were seen in women exposed to ciprofloxacin during pregnancy. However, these small postmarketing epidemiology studies, of which most experience is from short term, first trimester exposure, are insufficient to evaluate the risk for less common defects or to permit reliable and definitive conclusions regarding the safety of ciprofloxacin in pregnant women and their developing fetuses. Animal Data Developmental toxicology studies have been performed with ciprofloxacin in rats, mice, and rabbits. In rats and mice, oral doses up to 100 mg/kg administered during organogenesis (Gestation Days, GD, 6-17) were not associated with adverse developmental outcomes, including embryofetal toxicity or malformations. In rats and mice, a 100 mg/kg dose is approximately 0.6 and 0.3 times the maximum daily human oral dose (1500 mg/day) based upon body surface area, respectively. In a series of rabbit developmental toxicology studies, does received oral or intravenous ciprofloxacin for one of the following 5 day periods: GD 6 to 10, GD 10 to 14, or GD 14 to 18, intended to cover the period of organogenesis. This was an attempt to mitigate the gastrointestinal intolerance observed in rabbits that receive antibacterials manifested by reduced maternal food consumption and weight loss, that can lead to embryofetal resorption or spontaneous abortion. An oral ciprofloxacin dose of 100 mg/kg (approximately 1.3 times the highest recommended clinical oral dose based on body surface area) caused excessive maternal toxicity confounding evaluation of the fetuses. A 30 mg/kg oral dose (approximately 0.4 times the highest recommended clinical oral dose) was associated with suppression of maternal and fetal body weight gain, but fetal malformations were not observed. Intravenous administration of doses up to 20 mg/kg (approximately 0.3 times the highest recommended clinical oral dose based upon body surface area) to pregnant rabbits was not maternally toxic and neither embryofetal toxicity nor fetal malformations were observed. In peri-and post-natal studies, rats received ciprofloxacin doses up to 200 mg/kg/day (oral) or up to 30 mg/kg/day (subcutaneous) from GD 16 to 22 days postpartum. The 200 mg/kg dose is approximately 1.3-times the maximum recommended clinical oral dose based on body surface area. Neither maternal toxicity nor adverse effects on growth and development of the pups were observed, including no sign of arthropathy on the rear leg joints of the pups. Ciprofloxacin and other quinolones have been shown to cause arthropathy in immature animals of most species tested when administered directly [see Warnings and Precautions (5.13) and Nonclinical Toxicology 13.2 ]. 8.2 Lactation Risk Summary Published literature reports that ciprofloxacin is present in human milk following intravenous and oral administration . There is no information regarding effects of ciprofloxacin on milk production or the breastfed infant. Because of the potential risk of serious adverse reactions in breastfed infants, including arthropathy shown in juvenile animal studies [see Use in Specific Populations (8.4) , (Clinical Considerations)], for most indications a lactating woman may consider pumping and discarding breast milk during treatment with ciprofloxacin and an additional two days (five half-lives) after the last dose. Alternatively, advise a woman that breastfeeding is not recommended during treatment with ciprofloxacin and for an additional two days (five half-lives) after the last dose. However, for inhalation anthrax (post exposure), during an incident resulting in exposure to anthrax, the risk-benefit assessment of continuing breastfeeding while the mother (and potentially the infant) is (are) on ciprofloxacin may be acceptable [see Dosage and Administration (2.2) , Pediatric Use (8.4) , and Clinical Studies (14.2) ]. The developmental and health benefits of breastfeeding should be cons

In [ ]:
# Save results with tool calls to JSON file
output_path = "results/medqa_txagent_tool_calls.json"
import os
os.makedirs("results", exist_ok=True)

results_df.to_json(output_path, orient='records', indent=2)
print(f"Results saved to {output_path}")

print("\n=== Sample Result ===")
sample = results_df.iloc[0]
print(f"Query: {sample['query'][:200]}...")
print(f"Ground Truth: {sample['ground_truth']}")
print(f"Tool Calls:")
for tc in sample['tool_calls'] or []:
    print(f"  - Name: {tc['name']}")
    print(f"    Arguments: {tc['arguments']}")

In [16]:
# Create datasets for 2-model pipeline from TxAgent outputs
# Using SIMPLIFIED output format for better trainability
import json
import os
from collections import defaultdict

def create_training_datasets_v2(results_df, output_dir="datasets/finetuning"):
    """
    Create two datasets from TxAgent inference results with SIMPLIFIED formats:
    
    Model 1 (Tool Selection): Simpler text-based output format
    Model 2 (Reasoning): Question + tool results -> answer
    """
    os.makedirs(output_dir, exist_ok=True)
    
    model1_data = []  # Tool selection dataset
    model2_data = []  # Reasoning dataset
    
    for idx, row in results_df.iterrows():
        if not row.get('tool_calls') or len(row['tool_calls']) == 0:
            continue
            
        question = row['input']
        ground_truth = row['output']
        tool_calls = row['tool_calls']
        final_response = row.get('final_response', '')
        
        # ========== Model 1: Tool Selection Dataset (SIMPLIFIED) ==========
        # Group tool calls by tool name to show pattern
        tool_groups = defaultdict(list)
        for tc in tool_calls:
            name = tc.get('name', '')
            if name and name not in ['Finish', 'Tool_RAG']:
                args = tc.get('arguments', {})
                # Extract the key argument (usually drug_name)
                if isinstance(args, dict):
                    drug = args.get('drug_name', args.get('name', ''))
                    if drug:
                        tool_groups[name].append(drug)
                    else:
                        tool_groups[name].append(str(args))
                else:
                    tool_groups[name].append(str(args))
        
        if tool_groups:
            # Create simplified text output format
            # Format: TOOL_NAME: arg1, arg2, arg3
            output_lines = []
            for tool_name, args_list in tool_groups.items():
                unique_args = list(dict.fromkeys(args_list))  # Remove duplicates, preserve order
                output_lines.append(f"{tool_name}: {', '.join(unique_args)}")
            
            simplified_output = "\n".join(output_lines)
            
            model1_sample = {
                'instruction': "Identify the biomedical database tools and drug names needed to answer this medical question. Output format: TOOL_NAME: drug1, drug2, ...",
                'input': question,
                'output': simplified_output,
                'ground_truth_answer': ground_truth
            }
            model1_data.append(model1_sample)
        
        # ========== Model 2: Reasoning Dataset ==========
        # Input: Question + Tool results (formatted as readable text)
        # Output: Final answer with reasoning
        tool_results_text = []
        for tc in tool_calls:
            name = tc.get('name', '')
            if name and name not in ['Finish', 'Tool_RAG']:
                args = tc.get('arguments', {})
                result = tc.get('result', '')
                
                # Format arguments nicely
                if isinstance(args, dict):
                    args_str = ", ".join(f"{k}={v}" for k, v in args.items())
                else:
                    args_str = str(args)
                
                # Truncate very long results
                if isinstance(result, dict):
                    result = json.dumps(result)
                result_str = str(result)[:1500] if len(str(result)) > 1500 else str(result)
                
                tool_results_text.append(f"[{name}({args_str})]\n{result_str}")
        
        if tool_results_text and final_response:
            # Create readable input combining question and tool results
            model2_input = f"""QUESTION:
{question}

TOOL RESULTS:
{chr(10).join(tool_results_text)}"""
            
            model2_sample = {
                'instruction': "Based on the medical question and tool results, select the best answer option and explain your reasoning.",
                'input': model2_input,
                'output': final_response,
                'ground_truth_answer': ground_truth
            }
            model2_data.append(model2_sample)
    
    # Save datasets
    model1_path = os.path.join(output_dir, 'model1_tool_selection.json')
    model2_path = os.path.join(output_dir, 'model2_reasoning.json')
    
    with open(model1_path, 'w') as f:
        json.dump(model1_data, f, indent=2)
    
    with open(model2_path, 'w') as f:
        json.dump(model2_data, f, indent=2)
    
    print(f"✅ Model 1 (Tool Selection) dataset: {len(model1_data)} samples -> {model1_path}")
    print(f"✅ Model 2 (Reasoning) dataset: {len(model2_data)} samples -> {model2_path}")
    
    return model1_data, model2_data

# Generate datasets with simplified format
model1_data, model2_data = create_training_datasets_v2(results_df)

# Preview Model 1 sample
print("\n" + "="*80)
print("MODEL 1 SAMPLE - SIMPLIFIED FORMAT (Tool Selection)")
print("="*80)
if model1_data:
    sample = model1_data[0]
    print(f"INSTRUCTION: {sample['instruction']}")
    print(f"\nINPUT:\n{sample['input'][:300]}...")
    print(f"\nOUTPUT (what model learns to generate):\n{sample['output']}")
    print(f"\nGROUND TRUTH: {sample['ground_truth_answer']}")

# Preview Model 2 sample
print("\n" + "="*80)
print("MODEL 2 SAMPLE (Reasoning)")  
print("="*80)
if model2_data:
    sample = model2_data[0]
    print(f"INSTRUCTION: {sample['instruction']}")
    print(f"\nINPUT (first 500 chars):\n{sample['input'][:500]}...")
    print(f"\nOUTPUT (first 300 chars):\n{sample['output'][:300]}...")

## Dataset Format Summary

### Model 1: Tool Selection (LLaVA-Med Fine-tuning) - SIMPLIFIED FORMAT
**Purpose:** Learn which tools to call for a given medical question

**Why Simplified?** 
- Easier for model to learn consistent pattern
- Variable number of tools handled naturally
- No complex JSON escaping issues

| Field | Example |
|-------|---------|
| `instruction` | "Identify the biomedical database tools and drug names needed..." |
| `input` | Medical question with options |
| `output` | `FDA_get_pregnancy_effects_info_by_drug_name: Ampicillin, Nitrofurantoin` |

### Model 2: Reasoning Model
**Purpose:** Given question + tool results, reason to the correct answer

| Field | Description |
|-------|-------------|
| `instruction` | System prompt for reasoning task |
| `input` | Plain text: Question + formatted tool results |
| `output` | Final reasoning and answer selection |

### Pipeline Flow:
```
Question → Model 1 → "TOOL: drug1, drug2" → Parse → Execute APIs → Tool Results → Model 2 → Answer
```

### Advantages of Simplified Format:
1. **Consistent structure** - Always `TOOL_NAME: arg1, arg2, arg3`
2. **Easy to parse** - Simple string split on `:` and `,`
3. **Handles variable counts** - Model can output 1 or 20 drugs naturally
4. **No JSON errors** - Plain text is more robust than structured JSON
5. **Learnable pattern** - Model sees consistent format across all examples